// SPDX-License-Identifier: MIT OR Apache-2.0

//! Surface-capability inventory (PAR1): the four surfaces kept in view together.
//!
//! PAR1 is the JOIN -- which capability is reachable on which of CLI, TUI, REST
//! and MCP. Its raw material is the four inventories, and this file is the
//! anti-vacuity floor under them: `docs/design/surface-capability-inventory.md`
//! is generated by `scripts/capability-matrix.py` from the surfaces' own
//! sources, and a generated document is only worth reading while something
//! forces it to describe the program. Each surface is re-derived here and held
//! to the doc.
//!
//! Distinct from `surface_parity_test.rs`, which holds the quality METRICS to
//! symmetry across surfaces; this holds the surface INVENTORIES (flags, views,
//! routes, tools) to a generated doc that the capability JOIN builds on.
//!
//! Deliberately compares the SET, not the count: a gate on the count alone
//! passes when one item is added and another removed in the same change, and
//! says nothing about which.

#![cfg(feature = "full")]

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use clap::CommandFactory;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn inventory_doc() -> String {
    let p = root().join("docs/design/surface-capability-inventory.md");
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

/// Items the inventory doc lists under `## <title> (...)`, read from its
/// `- `backtick`` bullets until the next `## ` heading.
fn doc_section(doc: &str, title_prefix: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut inside = false;
    for line in doc.lines() {
        if let Some(heading) = line.strip_prefix("## ") {
            inside = heading.starts_with(title_prefix);
            continue;
        }
        if inside
            && let Some(rest) = line.strip_prefix("- `")
            && let Some(end) = rest.find('`')
        {
            out.insert(rest[..end].to_string());
        }
    }
    out
}

/// Every long flag clap knows about, hidden ones included (`hide` affects only
/// the help display, not the arg registry). This is the authoritative CLI
/// surface -- the generator reads `--help` plus the source for hidden flags to
/// reach the same set.
fn cli_flags() -> BTreeSet<String> {
    let cmd = sipnab::cli::Cli::command();
    let mut flags: BTreeSet<String> = cmd
        .get_arguments()
        .filter_map(|a| a.get_long().map(|l| format!("--{l}")))
        .collect();
    // clap generates `--help`/`--version` itself and does not return them from
    // `get_arguments()`, but they ARE flags a user can pass and the generator
    // reads them from `--help`, so the doc lists them. Add them on this side.
    flags.insert("--help".to_string());
    flags.insert("--version".to_string());
    flags
}

/// The `View` enum's variants -- the TUI's top-level surface.
fn tui_views() -> BTreeSet<String> {
    let src = std::fs::read_to_string(root().join("src/tui/state.rs")).expect("read state.rs");
    let start = src.find("pub enum View {").expect("View enum") + "pub enum View {".len();
    let body = &src[start..src[start..].find("\n}").expect("enum close") + start];
    let mut out = BTreeSet::new();
    for line in body.lines() {
        let t = line.trim_start();
        if t.starts_with("//") || t.starts_with("#[") {
            continue;
        }
        let ident: String = t.chars().take_while(|c| c.is_alphanumeric()).collect();
        if ident.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
            out.insert(ident);
        }
    }
    out
}

/// Every route axum registers, read from `src/output/api.rs` (`.route("...")`).
fn rest_routes() -> BTreeSet<String> {
    let api = std::fs::read_to_string(root().join("src/output/api.rs")).expect("read api.rs");
    let mut out = BTreeSet::new();
    for (i, _) in api.match_indices(".route(") {
        let rest = &api[i + ".route(".len()..];
        let Some(open) = rest.find('"') else {
            continue;
        };
        let Some(close) = rest[open + 1..].find('"') else {
            continue;
        };
        out.insert(rest[open + 1..open + 1 + close].to_string());
    }
    out
}

/// Every MCP tool, read from `#[tool(name = "...")]` across `src/mcp/`.
fn mcp_tools() -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut stack = vec![root().join("src/mcp")];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d).expect("read src/mcp").flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            let needle = "#[tool(";
            for (i, _) in text.match_indices(needle) {
                let after = &text[i + needle.len()..];
                let Some(endattr) = after.find(")]") else {
                    continue;
                };
                let Some(np) = after.find("name") else {
                    continue;
                };
                if np >= endattr {
                    continue;
                }
                let seg = &after[np..];
                let Some(open) = seg.find('"') else {
                    continue;
                };
                let Some(close) = seg[open + 1..].find('"') else {
                    continue;
                };
                out.insert(seg[open + 1..open + 1 + close].to_string());
            }
        }
    }
    out
}

/// A surface whose re-derived set differs from the inventory doc means the doc
/// has stopped describing the program. Reported per surface, set-not-count.
fn assert_surface(name: &str, title_prefix: &str, derived: &BTreeSet<String>, floor: usize) {
    let doc = inventory_doc();
    let listed = doc_section(&doc, title_prefix);

    assert!(
        derived.len() >= floor,
        "the {name} surface re-derived only {} items (floor {floor}); the scan \
         that reads it has stopped working, so this gate is certifying almost \
         nothing",
        derived.len()
    );

    let missing: Vec<_> = derived.difference(&listed).cloned().collect();
    let stale: Vec<_> = listed.difference(derived).cloned().collect();
    assert!(
        missing.is_empty() && stale.is_empty(),
        "docs/design/surface-capability-inventory.md no longer describes the \
         {name} surface.\n  missing from the doc ({}): {}\n  listed but gone \
         ({}): {}\n\nRegenerate:\n    cargo build --features full && python3 \
         scripts/capability-matrix.py --write",
        missing.len(),
        missing.join(", "),
        stale.len(),
        stale.join(", "),
    );
}

#[test]
fn the_inventory_lists_every_cli_flag() {
    assert_surface("CLI", "CLI flags", &cli_flags(), 100);
}

#[test]
fn the_inventory_lists_every_tui_view() {
    assert_surface("TUI", "TUI views", &tui_views(), 10);
}

#[test]
fn the_inventory_lists_every_rest_route() {
    assert_surface("REST", "REST routes", &rest_routes(), 10);
}

#[test]
fn the_inventory_lists_every_mcp_tool() {
    assert_surface("MCP", "MCP tools", &mcp_tools(), 40);
}
