// SPDX-License-Identifier: MIT OR Apache-2.0

//! The surface coverage matrix must list every flag sipnab actually has.
//!
//! `docs/design/testing-matrix.md` is generated by
//! `scripts/coverage-matrix.py`, and a generated document is only worth
//! reading while something forces it to be regenerated. Without this gate the
//! matrix rots the way every hand-maintained count in this repository has
//! rotted: it keeps rendering, keeps looking authoritative, and quietly stops
//! describing the program.
//!
//! Deliberately compares the SET and not the count. A gate on the count alone
//! passes when one flag is added and another removed in the same change --
//! and reports nothing about which.

#![cfg(feature = "full")]

use std::collections::BTreeSet;
use std::path::Path;

use clap::CommandFactory;

/// Every long flag clap knows about.
fn clap_long_flags() -> BTreeSet<String> {
    let cmd = sipnab::cli::Cli::command();
    let mut flags = BTreeSet::new();
    for arg in cmd.get_arguments() {
        if let Some(long) = arg.get_long() {
            flags.insert(format!("--{long}"));
        }
    }
    // clap generates `--help` and `--version` itself and does not return them
    // from `get_arguments()`, so they appear in `--help` output -- which the
    // generator reads -- and never here. `docs_drift_test` adds them back for
    // the same reason; this gate drops them from the other side of the
    // comparison instead, because the matrix documents flags this program
    // chose to have.
    flags
}

/// Every flag the matrix's CLI table lists, read from its first column.
fn matrix_flags(text: &str) -> BTreeSet<String> {
    text.lines()
        .filter(|l| l.starts_with("| `--"))
        .filter_map(|l| l.split('`').nth(1))
        .map(str::to_string)
        .collect()
}

#[test]
fn the_matrix_lists_every_flag_the_program_has() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/design/testing-matrix.md");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));

    let have = clap_long_flags();
    let listed = matrix_flags(&text);

    let missing: Vec<_> = have.difference(&listed).cloned().collect();
    let stale: Vec<_> = listed
        .difference(&have)
        .filter(|f| !matches!(f.as_str(), "--help" | "--version"))
        .cloned()
        .collect();

    assert!(
        missing.is_empty() && stale.is_empty(),
        "docs/design/testing-matrix.md no longer describes this program.\n\
         missing from the matrix ({}): {}\n\
         listed but no longer a flag ({}): {}\n\
         \n\
         Regenerate it:\n    \
         cargo build --features full && python3 scripts/coverage-matrix.py\n\
         \n\
         A flag that reaches users without a row here is a surface nobody has \
         had to say anything about the testing of, which is the state this \
         document exists to make visible.",
        missing.len(),
        missing.join(", "),
        stale.len(),
        stale.join(", "),
    );
}
