// SPDX-License-Identifier: MIT OR Apache-2.0

//! The surface coverage matrix must list every flag sipnab actually has.
//!
//! `docs/design/testing-matrix.md` is generated by
//! `scripts/coverage-matrix.py`, and a generated document is only worth
//! reading while something forces it to be regenerated. Without this gate the
//! matrix rots the way every hand-maintained count in this repository has
//! rotted: it keeps rendering, keeps looking authoritative, and quietly stops
//! describing the program.
//!
//! Deliberately compares the SET and not the count. A gate on the count alone
//! passes when one flag is added and another removed in the same change --
//! and reports nothing about which.

#![cfg(feature = "full")]

use std::collections::BTreeSet;
use std::path::Path;

use clap::CommandFactory;

/// Every long flag clap knows about.
fn clap_long_flags() -> BTreeSet<String> {
    let cmd = sipnab::cli::Cli::command();
    let mut flags = BTreeSet::new();
    for arg in cmd.get_arguments() {
        if let Some(long) = arg.get_long() {
            flags.insert(format!("--{long}"));
        }
    }
    // clap generates `--help` and `--version` itself and does not return them
    // from `get_arguments()`, so they appear in `--help` output -- which the
    // generator reads -- and never here. `docs_drift_test` adds them back for
    // the same reason; this gate drops them from the other side of the
    // comparison instead, because the matrix documents flags this program
    // chose to have.
    flags
}

/// Every flag the matrix's CLI table lists, read from its first column.
fn matrix_flags(text: &str) -> BTreeSet<String> {
    text.lines()
        .filter(|l| l.starts_with("| `--"))
        .filter_map(|l| l.split('`').nth(1))
        .map(str::to_string)
        .collect()
}

#[test]
fn the_matrix_lists_every_flag_the_program_has() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/design/testing-matrix.md");
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));

    let have = clap_long_flags();
    let listed = matrix_flags(&text);

    let missing: Vec<_> = have.difference(&listed).cloned().collect();
    let stale: Vec<_> = listed
        .difference(&have)
        .filter(|f| !matches!(f.as_str(), "--help" | "--version"))
        .cloned()
        .collect();

    assert!(
        missing.is_empty() && stale.is_empty(),
        "docs/design/testing-matrix.md no longer describes this program.\n\
         missing from the matrix ({}): {}\n\
         listed but no longer a flag ({}): {}\n\
         \n\
         Regenerate it:\n    \
         cargo build --features full && python3 scripts/coverage-matrix.py\n\
         \n\
         A flag that reaches users without a row here is a surface nobody has \
         had to say anything about the testing of, which is the state this \
         document exists to make visible.",
        missing.len(),
        missing.join(", "),
        stale.len(),
        stale.join(", "),
    );
}

/// Every HTTP route axum registers has a row, and none of them reads
/// `defined only`.
///
/// The second half is the assertion with teeth, and it is here because the
/// generator got it wrong in the direction that matters. Axum spells a path
/// parameter `{call_id}`; a test writes its own placeholder --
/// `format!("/v1/streams/{ssrc}")`, whose literal source text is what the
/// generator reads -- or a concrete value. Matching the route string literally,
/// all three of sipnab's parameterized routes reported `defined only` while
/// `tests/api_test.rs` was driving every one of them, including the call-report
/// route an operator reaches for first.
///
/// A document that understates coverage is as untrustworthy as one that
/// overstates it: both stop being read. If a route genuinely has no test, the
/// answer is to write the test, not to relax this.
#[test]
fn every_http_route_has_a_row_and_none_of_them_is_only_defined() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let matrix = std::fs::read_to_string(root.join("docs/design/testing-matrix.md"))
        .expect("read testing-matrix.md");
    let api = std::fs::read_to_string(root.join("src/output/api.rs")).expect("read api.rs");

    // Every `.route("...")` axum is handed, read from the source rather than
    // restated here -- a list written twice is a list that disagrees.
    let mut registered = BTreeSet::new();
    for (i, _) in api.match_indices(".route(") {
        let rest = &api[i + ".route(".len()..];
        let Some(open) = rest.find('"') else { continue };
        let Some(close) = rest[open + 1..].find('"') else {
            continue;
        };
        registered.insert(rest[open + 1..open + 1 + close].to_string());
    }
    assert!(
        registered.len() >= 5,
        "only {} routes were read out of api.rs, so this gate is comparing \
         almost nothing -- the `.route(` scan stopped working",
        registered.len()
    );

    // The matrix's route rows: `| `/v1/streams` | exercised | ... |`
    let mut rows = BTreeSet::new();
    let mut only_defined = Vec::new();
    for line in matrix.lines() {
        if !line.starts_with("| `/") {
            continue;
        }
        let mut cells = line.split('|').map(str::trim);
        cells.next();
        let Some(route) = cells.next().and_then(|c| c.split('`').nth(1)) else {
            continue;
        };
        let tier = cells.next().unwrap_or("");
        rows.insert(route.to_string());
        if tier == "defined only" || tier == "none" {
            only_defined.push(format!("{route} ({tier})"));
        }
    }

    let missing: Vec<_> = registered.difference(&rows).cloned().collect();
    assert!(
        missing.is_empty(),
        "routes with no row in docs/design/testing-matrix.md: {}\n\
         Regenerate: cargo build --features full && python3 scripts/coverage-matrix.py",
        missing.join(", ")
    );

    assert!(
        only_defined.is_empty(),
        "the matrix reports these routes as unexercised: {}\n\n\
         Either a test that drives them stopped being recognized -- check \
         `route_pattern` and `SERVER_DRIVERS` in scripts/coverage-matrix.py, \
         which is where this went wrong last time -- or the route really has no \
         test, and the fix is the test.",
        only_defined.join(", ")
    );
}
