// SPDX-License-Identifier: MIT OR Apache-2.0

//! Ratchet guard: every user-facing CLI flag must appear in at least two
//! runnable example commands in the documentation.
//!
//! Companion to `docs_drift_test` (which proves documented flags EXIST) and
//! `flag_coverage_test` (which proves flags are TESTED). This one proves flags
//! are DEMONSTRATED — the maintainer's "every parameter gets multiple
//! examples" requirement.
//!
//! Regression history: an audit on 2026-07-18 found 80 flags with zero
//! examples and 17 with one; grouped `**Examples**` blocks in
//! `docs/cli-reference.md` (+ website mirror) closed the gap to 135/135. This
//! test keeps it closed — a new flag added without two examples fails CI.
#![cfg(feature = "native")]

#[path = "support/markdown.rs"]
mod markdown;

use clap::CommandFactory;
use std::collections::BTreeMap;

/// Minimum example occurrences required per user-facing flag.
const MIN_EXAMPLES: usize = 2;

/// Flags that legitimately cannot carry a runnable example (none today).
/// Each entry MUST carry a written justification, mirroring the
/// `KNOWN_UNTESTED` ratchet convention in `flag_coverage_test.rs`.
const WAIVED: &[(&str, &str)] = &[
    // Hidden internal flag (clap `hide = true`, absent from --help): it
    // deliberately triggers a panic to exercise the crash-report hook. Not a
    // user-facing feature; documenting a "crash on purpose" flag with runnable
    // examples would be actively misleading.
    (
        "panic-selftest",
        "hidden internal panic-hook self-test, not user-facing",
    ),
    // Built-in API TLS is not wired up (axum-server not integrated): setting
    // these makes sipnab exit at startup. Documented as reverse-proxy-only, so
    // a runnable example would be a command that always errors.
    (
        "api-tls-cert",
        "API TLS not implemented; documented as reverse-proxy-only",
    ),
    (
        "api-tls-key",
        "API TLS not implemented; documented as reverse-proxy-only",
    ),
];

/// Every markdown doc that carries user-facing command examples. Read at
/// runtime from CARGO_MANIFEST_DIR so new docs are covered automatically.
///
/// # Returns
/// `(relative_path, file_text)` for each `.md` file in `docs/`,
/// `website/content/docs/`, and the top-level `README.md`; panics if the
/// corpus is suspiciously small (path resolution broken).
fn doc_corpus() -> Vec<(String, String)> {
    let root = env!("CARGO_MANIFEST_DIR");
    let mut docs = Vec::new();
    let mut mirrors_skipped = 0usize;
    for dir in ["docs", "website/content/docs"] {
        let path = std::path::Path::new(root).join(dir);
        let Ok(entries) = std::fs::read_dir(&path) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) == Some("md")
                && let Ok(text) = std::fs::read_to_string(&p)
            {
                // Skip generated mirrors. Thirteen pages under
                // website/content/docs/ are byte-for-byte copies of a page in
                // docs/, so every authored example in one was harvested twice
                // and MIN_EXAMPLES = 2 really meant "one authored example,
                // mirrored". The headline claim was already false: `--cores`
                // had exactly one authored example while this counted two, and
                // deleting one of a flag's two examples left the count at 2 —
                // the count could jump 2 -> 0 and never report 1, which is the
                // signature of a double count.
                //
                // Keyed on the banner the generator itself writes, so a new
                // mirror is excluded the day it appears rather than when
                // someone remembers to update a list here.
                if text.contains("<!-- Generated by scripts/") {
                    mirrors_skipped += 1;
                    continue;
                }
                docs.push((
                    format!("{dir}/{}", p.file_name().unwrap().to_string_lossy()),
                    text,
                ));
            }
        }
    }
    let readme = std::path::Path::new(root).join("README.md");
    if let Ok(text) = std::fs::read_to_string(&readme) {
        docs.push(("README.md".into(), text));
    }
    assert!(
        docs.len() > 15,
        "doc corpus suspiciously small ({}) — path resolution broken?",
        docs.len()
    );
    // The exclusion has to still be excluding. If the banner text changes and
    // nothing skips, every mirrored example is counted twice again and the
    // minimum quietly halves — the failure is invisible because the suite goes
    // GREENER, not redder.
    assert!(
        mirrors_skipped >= 10,
        "skipped only {mirrors_skipped} generated mirrors — the banner check \
         has stopped matching, so authored examples are being double-counted \
         and MIN_EXAMPLES is effectively half what it says"
    );
    docs
}

/// Concatenated text of every example command in the corpus: the body of
/// every ```bash fenced block, plus every inline-code span that is itself a
/// sipnab invocation.
///
/// Inline code counts because a fenced block is not the only way a doc
/// demonstrates a command. `docs/cli-reference.md` publishes its dense
/// per-section catalogs as markdown lists (``- `sipnab …` — what it does``)
/// so no surface can put a single copy button on a stack of unrelated
/// alternatives; those are still runnable examples and this ratchet must see
/// them. Harvesting only ```bash fences would have silently dropped 107 flags
/// below the minimum the moment the website mirror was regenerated.
///
/// The `sipnab` prefix is what keeps the ratchet honest: a flag named in a
/// reference table (`` `--json` ``) or in prose is not an example and is not
/// counted.
///
/// # Arguments
/// * `corpus` — `(path, text)` pairs from `doc_corpus`.
///
/// # Returns
/// All bash-fence bodies and inline sipnab commands, joined with newlines.
fn all_bash_blocks(corpus: &[(String, String)]) -> String {
    // Inline code spans, single-line only: ``…`` never wraps a line here.
    let inline = regex::Regex::new(r"`([^`\n]+)`").unwrap();
    let mut out = String::new();
    for (_, text) in corpus {
        for fence in markdown::fences(text) {
            if !matches!(fence.lang.as_str(), "bash" | "sh" | "shell" | "console") {
                continue;
            }
            // The SAME prefix filter the inline branch applies. The fence body
            // used to be pushed verbatim, so a ```bash block containing only
            // shell *comments* counted toward the minimum: replacing a flag's
            // two runnable examples with two `#` lines left this green,
            // counting four, with zero runnable examples anywhere. The
            // function's own docstring says the opposite — "a flag named in a
            // reference table … or in prose is not an example and is not
            // counted" — and that was true of one branch and not the other.
            for cmd in commands_in(&fence.body) {
                out.push_str(&cmd);
                out.push('\n');
            }
        }
        for cap in inline.captures_iter(text) {
            if is_invocation(cap[1].trim_start()) {
                out.push_str(&cap[1]);
                out.push('\n');
            }
        }
    }
    out
}

/// Whether a single logical line is a runnable sipnab invocation.
///
/// A pipeline counts — `cat x.pcap | sipnab -r -` demonstrates the flag just as
/// a bare invocation does — but a comment, a prompt with nothing after it, or
/// prose does not.
fn is_invocation(line: &str) -> bool {
    let line = line.trim_start().trim_start_matches("$ ").trim_start();
    if line.starts_with('#') {
        return false;
    }
    line.split('|')
        .map(str::trim_start)
        .any(|seg| seg.starts_with("sipnab ") || seg.starts_with("sudo sipnab "))
}

/// The runnable sipnab commands in a fence body, one logical line each.
///
/// A trailing `\` continues a command onto the next physical line, so the
/// lines are joined before the filter runs — otherwise a multi-line example
/// would contribute its first line and drop every flag on the rest.
fn commands_in(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    for line in body.lines() {
        let trimmed = line.trim_end();
        if let Some(head) = trimmed.strip_suffix('\\') {
            current.push_str(head.trim_end());
            current.push(' ');
            continue;
        }
        current.push_str(trimmed);
        let joined = std::mem::take(&mut current);
        if is_invocation(&joined) {
            out.push(joined);
        }
    }
    // An unterminated continuation still carries flags worth counting.
    if !current.is_empty() && is_invocation(&current) {
        out.push(current);
    }
    out
}

/// Primary long name of every user-facing flag (aliases and auto
/// help/version excluded — we count the canonical spelling only).
///
/// # Returns
/// The long flag names extracted from the clap `Cli` command definition.
fn user_facing_long_flags() -> Vec<String> {
    let cmd = sipnab::cli::Cli::command();
    let mut flags = Vec::new();
    for arg in cmd.get_arguments() {
        if let Some(long) = arg.get_long()
            && long != "help"
            && long != "version"
        {
            flags.push(long.to_string());
        }
    }
    flags
}

/// Every non-waived user-facing flag appears at least `MIN_EXAMPLES` (2) times
/// in the corpus's bash example blocks; under-demonstrated flags fail with a list.
#[test]
fn every_flag_has_at_least_two_examples() {
    let corpus = doc_corpus();
    let blocks = all_bash_blocks(&corpus);
    let waived: BTreeMap<&str, &str> = WAIVED.iter().copied().collect();

    let mut under = Vec::new();
    for flag in user_facing_long_flags() {
        if waived.contains_key(flag.as_str()) {
            continue;
        }
        // Count occurrences of `--flag` not followed by a flag char, so
        // `--api` doesn't match inside `--api-token-ttl`. The `regex` crate
        // has no look-ahead, so check the trailing byte by hand.
        let needle = format!("--{flag}");
        let n = blocks
            .match_indices(&needle)
            .filter(|(i, _)| {
                let after = i + needle.len();
                blocks[after..]
                    .chars()
                    .next()
                    .map(|c| !(c.is_ascii_alphanumeric() || c == '-'))
                    .unwrap_or(true)
            })
            .count();
        if n < MIN_EXAMPLES {
            under.push(format!("--{flag}: {n} example(s)"));
        }
    }
    under.sort();
    assert!(
        under.is_empty(),
        "{} flag(s) below the {MIN_EXAMPLES}-example minimum — add runnable \
         `**Examples**` blocks in docs/cli-reference.md (and mirror to the \
         website), or waive with justification:\n{}",
        under.len(),
        under.join("\n")
    );
}

/// Every entry in `WAIVED` still names a real flag — a waiver for a removed
/// flag fails so it gets cleaned up.
#[test]
fn waived_flags_still_exist() {
    // A waiver for a removed flag is dead weight — fail so it gets cleaned up.
    let real: std::collections::BTreeSet<String> = user_facing_long_flags().into_iter().collect();
    let stale: Vec<&str> = WAIVED
        .iter()
        .map(|(f, _)| *f)
        .filter(|f| !real.contains(*f))
        .collect();
    assert!(stale.is_empty(), "waivers for nonexistent flags: {stale:?}");
}
