// SPDX-License-Identifier: MIT OR Apache-2.0

//! The harness can swap its media anchor, and the swap is total.
//!
//! Given/When/Then over the compose file and the OpenSIPS entrypoint, because
//! the anchor is a property of the STACK rather than of any one container. A
//! swap that left half the old anchor running would produce a capture nobody
//! could interpret: two relays, one call, and no way to say which anchored it.
//!
//! These read configuration rather than a running stack on purpose. A test
//! that needs docker cannot run in CI, and the coupling worth holding is that
//! the files agree with each other.

#![cfg(feature = "full")]

use std::path::PathBuf;

fn harness(file: &str) -> String {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("harness")
        .join(file);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

fn compose() -> String {
    harness("docker-compose.yml")
}

fn entrypoint() -> String {
    harness("opensips/entrypoint.sh")
}

/// A port default as the COMPOSE FILE declares it, e.g. `${RTP_MIN:-30000}`.
///
/// Not from `harness/.env`: that file is generated by `make up` and git does
/// not track it, so tests reading it pass on a developer's machine and panic in
/// CI. The compose defaults are what ship, which makes them the honest source
/// for a rule about what the two anchors do.
fn compose_default(key: &str) -> u16 {
    let c = compose();
    let needle = format!("${{{key}:-");
    let at = c
        .find(&needle)
        .unwrap_or_else(|| panic!("{key} has no default in docker-compose.yml"));
    let rest = &c[at + needle.len()..];
    let end = rest
        .find('}')
        .unwrap_or_else(|| panic!("{key}'s default is unterminated"));
    rest[..end]
        .parse()
        .unwrap_or_else(|e| panic!("{key} default is not a port: {e}"))
}

// ── The anchor is a choice, and every value is real ──────────────────────────

/// GIVEN the OpenSIPS entrypoint
/// WHEN an anchor is selected
/// THEN all three values load a different relay module, or none at all.
#[test]
fn every_anchor_value_selects_a_real_configuration() {
    let e = entrypoint();
    assert!(e.contains(r#"loadmodule "rtpengine.so""#));
    assert!(e.contains(r#"loadmodule "rtpproxy.so""#));
    assert!(
        e.contains("MEDIA_ANCHOR=none: no relay module loaded"),
        "`none` must be a first-class value: it is the control the anchored \
         runs are measured against"
    );
}

/// GIVEN an unknown anchor name
/// WHEN the entrypoint runs
/// THEN it refuses loudly rather than defaulting to one silently.
#[test]
fn an_unknown_anchor_is_refused_not_defaulted() {
    let e = entrypoint();
    assert!(
        e.contains("FATAL: MEDIA_ANCHOR=") && e.contains("exit 1"),
        "a typo in the anchor name must not quietly run rtpengine"
    );
}

/// GIVEN each anchor
/// WHEN a call is offered
/// THEN the offer, answer and teardown all come from the SAME module family.
///
/// A half-swapped script -- rtpproxy offering and rtpengine deleting -- leaves
/// sessions on one relay forever, and the capture shows a call that never
/// tears down.
#[test]
fn an_anchor_offers_answers_and_tears_down_with_one_module() {
    let e = entrypoint();
    for verb in ["offer", "answer"] {
        assert!(
            e.contains(&format!("rtpengine_{verb}()")),
            "rtpengine is missing {verb}"
        );
        assert!(
            e.contains(&format!("rtpproxy_{verb}()")),
            "rtpproxy is missing {verb}"
        );
    }
    assert!(e.contains("rtpengine_delete()"), "rtpengine teardown");
    assert!(
        e.contains("rtpproxy_unforce()"),
        "rtpproxy tears down with unforce, not delete -- a different module's \
         spelling would not compile in the script"
    );
}

/// GIVEN the `none` anchor
/// WHEN a reply carrying SDP arrives
/// THEN the script still has a statement, because an empty route is rejected.
#[test]
fn the_control_anchor_still_produces_a_valid_script() {
    let e = entrypoint();
    assert!(
        e.contains("return;   # MEDIA_ANCHOR=none"),
        "OpenSIPS rejects an EMPTY onreply_route; the control run needs a real \
         statement rather than a comment"
    );
}

// ── One anchor at a time ─────────────────────────────────────────────────────

/// GIVEN the compose file
/// WHEN both relays are defined
/// THEN each sits behind its own profile, so only one runs.
#[test]
fn each_anchor_sits_behind_its_own_profile() {
    let c = compose();
    assert!(c.contains(r#"profiles: ["rtpengine"]"#));
    assert!(c.contains(r#"profiles: ["rtpproxy"]"#));
}

/// GIVEN a stack already running one anchor
/// WHEN another is selected
/// THEN the Makefile removes the previous anchor's containers.
#[test]
fn selecting_an_anchor_removes_the_other_ones_containers() {
    let m = harness("Makefile");
    assert!(
        m.contains("stop-other-anchors"),
        "without this the old relay keeps running and the capture has two"
    );
    assert!(m.contains("sipnab-relay-rtpproxy") && m.contains("rtpproxy"));
}

/// Every `host:container` port publication in one service block.
///
/// Reads the compose file's own defaults, never `harness/.env`: that file is
/// generated by `make up` and git does not track it.
fn published_host_ports(service: &str) -> Vec<String> {
    let c = compose();
    let at = c
        .find(&format!("\n  {service}:\n"))
        .unwrap_or_else(|| panic!("no service `{service}` in docker-compose.yml"));
    let rest = &c[at + 1..];
    // The block runs to the next top-level (two-space) service key.
    let end = rest
        .match_indices("\n  ")
        .find(|(i, _)| {
            let line = &rest[i + 3..];
            line.starts_with(|ch: char| ch.is_alphanumeric())
                && line.split(':').next().is_some_and(|k| !k.contains(' '))
                && *i > 0
        })
        .map_or(rest.len(), |(i, _)| i);
    // Non-greedy up to the `:<container port>`, so a RANGE
    // (`${RTP_MIN:-30000}-${RTP_MAX:-30050}`) is captured whole rather than
    // truncated at its first colon. Then every `${VAR:-N}` is resolved to its
    // default: comparing the VARIABLE names would call two different names
    // with the same number disjoint, which is exactly the collision this is
    // here to catch.
    let resolve = regex::Regex::new(r"\$\{[A-Z_]+:-([^}]+)\}").expect("regex");
    regex::Regex::new(r#"- "\$\{HARNESS_BIND:-[^}]+\}:(.+?):\d"#)
        .expect("regex")
        .captures_iter(&rest[..end])
        .map(|m| resolve.replace_all(&m[1], "$1").into_owned())
        .collect()
}

/// GIVEN rtpengine and rtpproxy, installed on the same host
/// WHEN both are brought up
/// THEN no host port is published by both, so neither refuses to start.
///
/// This test once asserted the OPPOSITE: that both anchors publish the SAME
/// host ports, on the reasoning that a swap should not be a new set of doors to
/// learn. That reasoning was about swapping. It made running both at once
/// impossible, and `docker compose up rtpengine` beside a running rtpproxy
/// failed with `Bind for 127.0.0.1:8081 failed: port is already allocated`.
///
/// **Norm, 2026-09-12:** "you must install rtpproxy the same server(es) as
/// rtpengine. this way, testing rtpengine and/or rtpproxy can be done in a
/// similar fashion. the rtp port ranges for rtpproxy and rtpengine must not
/// overlap."
///
/// Separating the media ranges and leaving the control doors colliding was half
/// a fix: the range separation only buys anything if both can run, and they
/// could not.
#[test]
fn the_two_relays_publish_no_host_port_in_common() {
    let engine = published_host_ports("rtpengine");
    let proxy = published_host_ports("rtpproxy");
    assert!(
        engine.len() >= 3 && proxy.len() >= 3,
        "the port extraction found {} rtpengine and {} rtpproxy publication(s) \
         ({engine:?} / {proxy:?}) — it is not reading the service blocks, so \
         any separation it certifies is unfounded",
        engine.len(),
        proxy.len()
    );
    let shared: Vec<&String> = engine.iter().filter(|p| proxy.contains(p)).collect();
    assert!(
        shared.is_empty(),
        "rtpengine and rtpproxy both publish host port(s) {shared:?}. Docker \
         refuses the second bind, so only one relay can run and the two cannot \
         be compared against one stack.\n  rtpengine: {engine:?}\n  rtpproxy:  {proxy:?}"
    );
}

/// GIVEN each relay's sidecar doors
/// WHEN a reader looks for one
/// THEN the variable naming it says which relay it belongs to.
///
/// Two REST ports called `RELAY_API_PORT` and `RELAY_API_PORT` is how they
/// collided. A name that does not distinguish them invites the next edit to
/// point both at one number again.
#[test]
fn each_relays_doors_are_named_after_the_relay_that_owns_them() {
    let c = compose();
    for (var, relay) in [
        ("RTPENGINE_API_PORT", "rtpengine"),
        ("RTPENGINE_MCP_PORT", "rtpengine"),
        ("RTPPROXY_API_PORT", "rtpproxy"),
        ("RTPPROXY_MCP_PORT", "rtpproxy"),
    ] {
        assert!(
            c.contains(&format!("${{{var}:-")),
            "docker-compose.yml declares no default for {var}, so {relay}'s \
             door is either unnamed or shares another relay's variable"
        );
    }
}

/// GIVEN a relay's published door
/// WHEN the sidecar behind it binds a port
/// THEN the CONTAINER side of the publication is the port it binds.
///
/// Only the HOST side moves to separate the two relays. Both sidecars are the
/// same image with the same configuration, so a publication whose container
/// side drifted from `API_BIND` would publish a closed port and report success.
#[test]
fn each_published_door_reaches_the_port_its_sidecar_binds() {
    let c = compose();
    let pairs = |service: &str| -> Vec<(String, String)> {
        let at = c
            .find(&format!("\n  {service}:\n"))
            .unwrap_or_else(|| panic!("no service `{service}`"));
        let rest = &c[at + 1..];
        let end = rest.find("\n    networks:").unwrap_or(rest.len());
        let resolve = regex::Regex::new(r"\$\{[A-Z_]+:-([^}]+)\}").expect("regex");
        regex::Regex::new(r#"- "\$\{HARNESS_BIND:-[^}]+\}:(.+?):([0-9-]+)/"#)
            .expect("regex")
            .captures_iter(&rest[..end])
            .map(|m| {
                (
                    resolve.replace_all(&m[1], "$1").into_owned(),
                    m[2].to_string(),
                )
            })
            .collect()
    };
    for (service, sidecar) in [
        ("rtpengine", "sipnab-relay"),
        ("rtpproxy", "sipnab-relay-rtpproxy"),
    ] {
        let published = pairs(service);
        assert!(
            published.len() >= 3,
            "only {} publication(s) parsed for {service}: {published:?}",
            published.len()
        );
        let at = c
            .find(&format!("\n  {sidecar}:\n"))
            .unwrap_or_else(|| panic!("no sidecar service `{sidecar}`"));
        let block = &c[at..];
        let block = &block[..block[1..].find("\n  s").map_or(block.len(), |i| i + 1)];
        for (host, container) in &published {
            // A RANGE is media, which the relay binds and the sidecar does not.
            // Anything else must be one of the two doors -- an earlier version
            // of this used `_ => continue`, and pointing the publication at
            // container port 8099 (which nothing binds) left it green. A guard
            // that skips the case it exists to catch is not a guard.
            if container.contains('-') {
                continue;
            }
            let bind = match container.as_str() {
                "8081" => "API_BIND: 0.0.0.0:8081",
                "8732" => "MCP_BIND: 0.0.0.0:8732",
                other => panic!(
                    "{service} publishes host {host} to container port {other}, \
                     which is neither a media range nor either of the sidecar's \
                     two doors (8081 REST, 8732 MCP). Nothing binds it."
                ),
            };
            assert!(
                block.contains(bind),
                "{service} publishes host {host} to container {container}, but \
                 {sidecar} has no `{bind}` — the door opens onto nothing"
            );
        }
    }
}

/// GIVEN the end-to-end script
/// WHEN it asks the relay what it saw
/// THEN it derives the door from the running anchor rather than assuming one.
///
/// The two relays publish different host ports now. A script that hardcodes
/// one reports "relay silent" against a perfectly healthy run of the other,
/// which reads as a capture defect rather than as a script talking to the
/// wrong door.
#[test]
fn the_e2e_script_finds_the_door_of_whichever_relay_is_anchoring() {
    // Read by its repo-relative path rather than through `harness()`, which
    // prefixes `harness/`: `every_cited_script_exists` resolves a cited script
    // from the repo root, and the helper's argument spells one that is not
    // there. Splitting the literal to get past that scanner would be hiding
    // from a gate that is right.
    let sh = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("harness/scripts/run-e2e.sh"),
    )
    .expect("harness/scripts/run-e2e.sh");
    assert!(
        sh.contains("MEDIA_ANCHOR="),
        "harness/scripts/run-e2e.sh does not ask the running stack which relay \
         is anchoring, so its relay door is a guess"
    );
    for port in ["8081", "8082"] {
        assert!(
            sh.contains(port),
            "harness/scripts/run-e2e.sh never mentions {port}; it can only \
             reach one of the two relays"
        );
    }
}

// ── sipnab watches the control plane of whichever anchor runs ────────────────

/// GIVEN the rtpproxy profile
/// WHEN sipnab captures beside it
/// THEN its capture filter includes rtpproxy's control port.
///
/// This was written into the harness BEFORE a decoder existed, so the evidence
/// would be in the pcap when one arrived. It has arrived.
#[test]
fn sipnab_captures_the_rtpproxy_control_port() {
    let c = compose();
    assert!(
        c.contains(r#"CONTROL_PORTS: "22223""#),
        "the rtpproxy relay instance must watch the control socket, or the \
         command exchange is not in the capture at all"
    );
}

/// GIVEN the rtpproxy container
/// WHEN OpenSIPS is configured to reach it
/// THEN both name the SAME control socket.
#[test]
fn opensips_and_rtpproxy_agree_on_the_control_socket() {
    let c = compose();
    assert!(
        c.contains("RTPPROXY_CTL_BIND: ${RTPPROXY_IP:-172.28.0.12}:22223"),
        "the relay binds its control socket here"
    );
    assert!(
        c.contains("22223"),
        "and OpenSIPS must be pointed at the same one"
    );
}

/// GIVEN rtpproxy anchoring media
/// WHEN sipnab runs beside it
/// THEN it does not expect HEP, because rtpproxy mirrors nothing.
#[test]
fn the_rtpproxy_instance_does_not_expect_hep() {
    let c = compose();
    // Read the service block by INDENTATION, not by a character count. A fixed
    // window expires the moment the block grows, and it would have been read
    // as a pass here rather than as a stale test.
    let mut in_block = false;
    let mut keys = Vec::new();
    for line in c.lines() {
        if line.trim_start().starts_with("sipnab-relay-rtpproxy:") {
            in_block = true;
            continue;
        }
        if in_block {
            let indent = line.len() - line.trim_start().len();
            if !line.trim().is_empty() && indent <= 2 {
                break;
            }
            // The SETTING, not the prose. The block carries a comment saying
            // why HEP is absent, and matching that would pass for the wrong
            // reason -- a test satisfied by an explanation rather than by the
            // configuration it explains.
            if let Some((key, _)) = line.trim().split_once(':')
                && !line.trim_start().starts_with('#')
            {
                keys.push(key.trim().to_string());
            }
        }
    }
    assert!(in_block, "the rtpproxy relay instance is defined");
    assert!(
        !keys.iter().any(|k| k == "HEP_PARSE"),
        "rtpproxy has no HEP mirror; asking for one would make every run \
         report a mirror that was never configured. Keys: {keys:?}"
    );
    assert!(
        keys.iter().any(|k| k == "CONTROL_PORTS"),
        "and the block must really have been read, or this proves nothing: \
         {keys:?}"
    );
}

// ── The two anchors never contend for a port ─────────────────────────────────

/// GIVEN both anchors defined in one stack
/// WHEN their media ranges are compared
/// THEN the ranges are disjoint.
///
/// They could have shared one: the profiles are mutually exclusive, so only a
/// Makefile target stops both running. "Safe because nobody can run both" is a
/// rule enforced somewhere other than the numbers, and a capture holding two
/// anchors on one port pair is one nobody can interpret.
#[test]
fn the_two_anchors_media_ranges_do_not_overlap() {
    let value = compose_default;
    let (engine_lo, engine_hi) = (value("RTP_MIN"), value("RTP_MAX"));
    let (proxy_lo, proxy_hi) = (value("RTPPROXY_RTP_MIN"), value("RTPPROXY_RTP_MAX"));

    assert!(engine_lo <= engine_hi, "rtpengine range is inverted");
    assert!(proxy_lo <= proxy_hi, "rtpproxy range is inverted");
    assert!(
        engine_hi < proxy_lo || proxy_hi < engine_lo,
        "the ranges overlap: rtpengine {engine_lo}-{engine_hi} and rtpproxy \
         {proxy_lo}-{proxy_hi}. A call anchored by one would land on ports the \
         other claims."
    );
}

/// GIVEN the two ranges
/// WHEN the gap between them is measured
/// THEN it is wide enough that an accidental overlap is obvious.
///
/// Adjacent ranges are disjoint and still a trap: moving either boundary by
/// one collides, and a one-port collision shows up as a single one-way call
/// nobody connects to a configuration change.
#[test]
fn the_gap_between_the_ranges_is_visible_not_incidental() {
    let value = compose_default;
    let engine_hi = value("RTP_MAX");
    let proxy_lo = value("RTPPROXY_RTP_MIN");
    let gap = proxy_lo.saturating_sub(engine_hi);
    assert!(
        gap >= 100,
        "only {gap} port(s) between the ranges; a boundary edited by hand \
         should not be able to collide without somebody noticing"
    );
}

/// GIVEN the rtpproxy container
/// WHEN it publishes media ports
/// THEN it publishes its OWN range and not the other anchor's.
#[test]
fn each_anchor_publishes_the_range_it_actually_uses() {
    let c = compose();
    assert!(
        c.contains("${RTPPROXY_RTP_MIN:-31000}-${RTPPROXY_RTP_MAX:-31050}:31000-31050/udp"),
        "rtpproxy must publish its own range, or the container allocates ports \
         nothing forwards and every call is one-way"
    );
    assert!(
        c.contains("${RTP_MIN:-30000}-${RTP_MAX:-30050}:30000-30050/udp"),
        "and rtpengine must keep publishing its own"
    );
}

/// GIVEN the rtpproxy container
/// WHEN it is told which ports to allocate from
/// THEN it is told its own range, not the shared default.
#[test]
fn the_relay_is_told_the_same_range_that_is_published() {
    let c = compose();
    let mut in_block = false;
    let mut min = None;
    let mut max = None;
    for line in c.lines() {
        if line.trim_start().starts_with("rtpproxy:") {
            in_block = true;
            continue;
        }
        if in_block {
            let indent = line.len() - line.trim_start().len();
            if !line.trim().is_empty() && indent <= 2 {
                break;
            }
            if let Some(v) = line.trim().strip_prefix("RTP_MIN:") {
                min = Some(v.trim().to_string());
            }
            if let Some(v) = line.trim().strip_prefix("RTP_MAX:") {
                max = Some(v.trim().to_string());
            }
        }
    }
    assert_eq!(
        min.as_deref(),
        Some("${RTPPROXY_RTP_MIN:-31000}"),
        "the relay allocates from the range it was told, and publishing one \
         while allocating from another is a silent one-way call"
    );
    assert_eq!(max.as_deref(), Some("${RTPPROXY_RTP_MAX:-31050}"));
}
