// SPDX-License-Identifier: MIT OR Apache-2.0

//! The OpenAPI document, the router that serves it, and the written reference
//! must describe one API.
//!
//! # The gap this exists to close
//!
//! `docs/rest-api.md` is 1,539 hand-written lines describing twelve
//! operations: their parameters, their response shapes, and their status
//! codes. Nothing compared it to the router. A route added without a heading
//! was invisible to a reader; a heading left behind after a route moved sent
//! one at a 404. Both are the ordinary way an API reference rots, and both
//! were reachable with the whole suite green.
//!
//! `website/static/openapi.json` is the machine-readable half, and it is
//! GENERATED — from the `#[utoipa::path]` annotations on the handlers
//! themselves. The generator is [`generate`] below, which is to say the
//! artifact is produced by a test step and not by hand. Regenerate it with:
//!
//! ```text
//! SIPNAB_BLESS_OPENAPI=1 cargo test --features full --test openapi_contract_test
//! ```
//!
//! `scripts/check-generated-inputs-staged.py` refuses a commit that stages the
//! artifact while an input to it sits unstaged in the working tree, which is
//! the failure no test can catch after the fact.
//!
//! # Why the whole file is feature-gated
//!
//! `--features full` is the build the published document describes.
//! `/v1/dialogs/{call_id}/vcon` is registered by `build_router` only where the
//! `vcon` exporter exists and appears in the document only under the same
//! `cfg`, so a document generated by a lesser build is a DIFFERENT and equally
//! correct document — comparing it to the artifact would fail for a reason
//! that is not a defect. The gate is on the crate and not on each test, so a
//! reduced-feature run compiles this file to nothing rather than to a test
//! that silently passes.

#![cfg(all(feature = "api", feature = "vcon", feature = "native"))]

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use serde_json::Value;

#[path = "support/server.rs"]
mod server;

/// The repository root.
fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// The published document, served at `https://sipnab.com/openapi.json`.
const ARTIFACT: &str = "website/static/openapi.json";

/// The hand-written reference the document must not contradict.
const WRITTEN: &str = "docs/rest-api.md";

/// Components taken from the canonical JSON Schemas rather than declared twice.
///
/// Each of these files already describes exactly one REST response body.
/// Declaring the same shape a second time in `src/output/api.rs` would create
/// precisely the drift this document is meant to remove, so the generator
/// splices the file in over the empty marker component the annotation
/// reserves, and `every_documented_response_matches_what_the_server_sends`
/// below validates a real response against the result.
///
/// `tests/json_schema_test.rs` checks `call_report.schema.json` a second way,
/// against `--call-report --json`. Its own header records that
/// `stream.schema.json` had no live-output check at all, which is the gap that
/// test closes.
const SPLICED: [(&str, &str); 2] = [
    ("CallReport", "call_report.schema.json"),
    ("RtpStream", "stream.schema.json"),
];

/// A capture with real dialogs AND real media, so every collection route has
/// something to answer with.
const G711: &str = "tests/pcap-samples/sip-rtp-g711.pcap";

// ── The generator ───────────────────────────────────────────────────

/// Rewrite every `$ref` in `node` through `f`.
fn map_refs(node: &mut Value, f: &dyn Fn(&str) -> Option<String>) {
    match node {
        Value::Object(map) => {
            if let Some(Value::String(r)) = map.get("$ref")
                && let Some(replacement) = f(r)
            {
                map.insert("$ref".to_string(), Value::String(replacement));
            }
            for (_, v) in map.iter_mut() {
                map_refs(v, f);
            }
        }
        Value::Array(items) => {
            for v in items {
                map_refs(v, f);
            }
        }
        _ => {}
    }
}

/// Load one shared JSON Schema as a set of OpenAPI components.
///
/// A `$defs` subschema cannot come across untouched: `#/$defs/x` resolves
/// against the DOCUMENT root, so once the schema is nested under
/// `components/schemas/` its own internal references point at a `$defs` table
/// that is not there. Each entry is therefore hoisted to a component of its
/// own, named `<Component>_<def>`, and the references are rewritten to match.
///
/// # Returns
///
/// The component name to schema pairs to insert, the head of the list being
/// the schema itself.
fn shared_schema(component: &str, file: &str) -> Vec<(String, Value)> {
    let path = repo().join("tests/schemas").join(file);
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut schema: Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{file} is not JSON: {e}"));

    let obj = schema
        .as_object_mut()
        .unwrap_or_else(|| panic!("{file} must be a JSON object"));
    // Document-level keywords. Inside `components/schemas` they would declare
    // a second schema document nested in the first.
    obj.remove("$schema");
    obj.remove("$id");
    let defs = obj.remove("$defs");

    let rename = |r: &str| -> Option<String> {
        r.strip_prefix("#/$defs/")
            .map(|name| format!("#/components/schemas/{component}_{name}"))
    };

    let mut out: Vec<(String, Value)> = Vec::new();
    map_refs(&mut schema, &rename);
    out.push((component.to_string(), schema));

    if let Some(Value::Object(defs)) = defs {
        for (name, mut def) in defs {
            map_refs(&mut def, &rename);
            out.push((format!("{component}_{name}"), def));
        }
    }
    out
}

/// The published document: what this crate generates, plus the shared schemas.
///
/// # Panics
///
/// On any malformed input, which is the point — a generator that shrugged and
/// emitted a smaller document would publish a contract missing the very parts
/// that failed to load.
fn generate() -> String {
    let mut doc: Value = serde_json::from_str(&sipnab::output::api::openapi_json())
        .expect("openapi_json() emits JSON");

    let schemas = doc
        .pointer_mut("/components/schemas")
        .and_then(Value::as_object_mut)
        .expect("the document declares components.schemas");
    for (component, file) in SPLICED {
        assert!(
            schemas.contains_key(component),
            "the annotations no longer reserve a `{component}` component, so \
             splicing {file} in would add a schema nothing references"
        );
        for (name, schema) in shared_schema(component, file) {
            schemas.insert(name, schema);
        }
    }

    let mut out = serde_json::to_string_pretty(&doc).expect("document serializes");
    out.push('\n');
    out
}

/// The document as generated right now.
fn document() -> Value {
    serde_json::from_str(&generate()).expect("generated document parses")
}

/// The HTTP methods an OpenAPI path item may carry.
const METHODS: [&str; 7] = ["get", "put", "post", "delete", "options", "head", "patch"];

/// Every `(method, path)` the document declares.
fn documented_operations(doc: &Value) -> BTreeSet<(String, String)> {
    let paths = doc["paths"]
        .as_object()
        .expect("the document declares paths");
    let mut out = BTreeSet::new();
    for (path, item) in paths {
        let item = item.as_object().expect("a path item is an object");
        for method in METHODS {
            if item.contains_key(method) {
                out.insert((method.to_string(), path.clone()));
            }
        }
    }
    out
}

// ── Deriving the route list from the source ─────────────────────────

/// Every `(method, path)` `build_router` registers, read out of its source.
///
/// Read from the SOURCE rather than from the built `Router`, because axum
/// exposes no way to enumerate a router's routes — and because a source scan
/// sees a `.route(...)` that a `cfg` would have removed, which is what makes
/// it able to notice a route added to a build this test is not running.
fn router_operations() -> BTreeSet<(String, String)> {
    let src = std::fs::read_to_string(repo().join("src/output/api.rs")).expect("read api.rs");
    let mut out = BTreeSet::new();
    let mut rest = src.as_str();

    while let Some(at) = rest.find(".route(") {
        let after = &rest[at + ".route(".len()..];
        // The argument list, by paren balance. A regex cannot do this: the
        // method chain `get(x).post(y)` carries parentheses of its own.
        let mut depth = 1usize;
        let mut end = None;
        for (i, c) in after.char_indices() {
            match c {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        end = Some(i);
                        break;
                    }
                }
                _ => {}
            }
        }
        let Some(end) = end else { break };
        let args = &after[..end];
        rest = &after[end..];

        // The path literal is the first argument.
        let Some(open) = args.find('"') else { continue };
        let Some(close) = args[open + 1..].find('"') else {
            continue;
        };
        let path = &args[open + 1..open + 1 + close];
        let handlers = &args[open + 1 + close..];

        for method in METHODS {
            let needle = format!("{method}(");
            let mut from = 0usize;
            while let Some(hit) = handlers[from..].find(&needle) {
                let abs = from + hit;
                // `get(` must be a token, not the tail of `something_get(`.
                let boundary = abs == 0
                    || !handlers[..abs]
                        .chars()
                        .next_back()
                        .is_some_and(|c| c.is_alphanumeric() || c == '_');
                if boundary {
                    out.insert((method.to_string(), path.to_string()));
                }
                from = abs + needle.len();
            }
        }
    }
    out
}

/// Every `(method, path)` `docs/rest-api.md` gives a heading to.
///
/// The page spells path parameters the axum 0.7 way (`:call_id`); the router
/// and the document use axum 0.8's (`{call_id}`). Normalized here rather than
/// rewritten in the page: the page's spelling is what its own anchors and
/// every inbound link use.
fn written_operations() -> BTreeSet<(String, String)> {
    let text = std::fs::read_to_string(repo().join(WRITTEN)).expect("read the written reference");
    let mut out = BTreeSet::new();
    for line in text.lines() {
        let Some(heading) = line.strip_prefix("### ") else {
            continue;
        };
        let mut parts = heading.split_whitespace();
        let (Some(method), Some(path)) = (parts.next(), parts.next()) else {
            continue;
        };
        if parts.next().is_some() || !path.starts_with('/') {
            continue;
        }
        let method = method.to_ascii_lowercase();
        if !METHODS.contains(&method.as_str()) {
            continue;
        }
        let normalized = path
            .split('/')
            .map(|seg| {
                seg.strip_prefix(':')
                    .map_or_else(|| seg.to_string(), |name| format!("{{{name}}}"))
            })
            .collect::<Vec<_>>()
            .join("/");
        out.insert((method, normalized));
    }
    out
}

/// Operations every derivation must find, whatever else it finds.
///
/// A scanner that matches nothing agrees with any document, so each derivation
/// is checked against a floor AND against these by name. The floor alone would
/// pass a scanner that found twelve of something else.
const ANCHORS: [(&str, &str); 4] = [
    ("get", "/health"),
    ("get", "/v1/dialogs/{call_id}"),
    ("post", "/v1/persistence"),
    ("get", "/metrics"),
];

/// Operations the REST surface has today.
///
/// A floor and not an equality: this test must fail when a route is added
/// without being documented, not when one is added at all.
const MINIMUM_OPERATIONS: usize = 12;

/// Assert a derived set is big enough and contains the anchors.
fn assert_derivation_found_something(what: &str, found: &BTreeSet<(String, String)>) {
    assert!(
        found.len() >= MINIMUM_OPERATIONS,
        "the {what} derivation found {} operations, fewer than the {MINIMUM_OPERATIONS} \
         the REST surface has had since 0.5.125 — the scan is broken, and a scan \
         that matches nothing agrees with any document: {found:?}",
        found.len()
    );
    for anchor in ANCHORS {
        let key = (anchor.0.to_string(), anchor.1.to_string());
        assert!(
            found.contains(&key),
            "the {what} derivation missed {} {}, which it must find by \
             construction — the scan does not do what this test believes",
            anchor.0.to_uppercase(),
            anchor.1
        );
    }
}

// ── The gates ───────────────────────────────────────────────────────

/// Every route the server serves is in the document, and nothing else is.
#[test]
fn the_document_describes_exactly_the_routes_the_router_serves() {
    let router = router_operations();
    assert_derivation_found_something("router", &router);

    let doc = document();
    let documented = documented_operations(&doc);
    assert_derivation_found_something("document", &documented);

    let undocumented: Vec<_> = router.difference(&documented).collect();
    assert!(
        undocumented.is_empty(),
        "build_router registers these and the OpenAPI document does not \
         describe them — add a #[utoipa::path] to the handler: {undocumented:?}"
    );

    let invented: Vec<_> = documented.difference(&router).collect();
    assert!(
        invented.is_empty(),
        "the OpenAPI document advertises these and build_router serves none of \
         them — a client following the document would get a 404: {invented:?}"
    );
}

/// The document and the written reference describe the same routes.
#[test]
fn the_document_and_the_written_reference_agree() {
    let written = written_operations();
    assert_derivation_found_something("written reference", &written);

    let doc = document();
    let documented = documented_operations(&doc);

    let unwritten: Vec<_> = documented.difference(&written).collect();
    assert!(
        unwritten.is_empty(),
        "the OpenAPI document describes these and {WRITTEN} has no `### METHOD \
         /path` heading for them — a reader of the page cannot find them: \
         {unwritten:?}"
    );

    let stale: Vec<_> = written.difference(&documented).collect();
    assert!(
        stale.is_empty(),
        "{WRITTEN} documents these and the OpenAPI document does not — either \
         the route was removed and the page still advertises it, or the \
         handler lost its annotation: {stale:?}"
    );
}

/// The document is a valid OpenAPI 3.1 document.
///
/// Structural, not meta-schema: the OpenAPI 3.1 meta-schema lives at
/// `spec.openapis.org` and the test suite has no network. What is checked here
/// is everything a consumer would actually break on — the version, the
/// required `info` members, that every operation declares responses, that
/// every `$ref` resolves, and that each component compiles as a JSON Schema
/// with `jsonschema`, which is how `tests/json_schema_test.rs` proves a schema
/// well-formed.
#[test]
fn the_document_is_valid_openapi_31() {
    // BOTH the document this crate generates and the file the website serves.
    // Checking only the generated one leaves the published artifact validated
    // by nothing but the drift gate beside it, and the two answer different
    // questions: drift says "these are equal", validity says "this is an
    // OpenAPI document". Corrupting the artifact's version field proved the
    // gap -- the drift gate fired and this one did not.
    assert_valid_openapi_31("the generated document", &document());

    let artifact: Value = serde_json::from_str(
        &std::fs::read_to_string(repo().join(ARTIFACT)).unwrap_or_else(|e| {
            panic!("{ARTIFACT} must exist and be readable to be validated: {e}")
        }),
    )
    .unwrap_or_else(|e| panic!("{ARTIFACT} is not JSON: {e}"));
    assert_valid_openapi_31(ARTIFACT, &artifact);
}

/// Everything a consumer of an OpenAPI 3.1 document would break on.
fn assert_valid_openapi_31(what: &str, doc: &Value) {
    let doc = doc.clone();

    assert_eq!(
        doc["openapi"].as_str(),
        Some("3.1.0"),
        "{what} must declare OpenAPI 3.1.0; 3.0.x has a different, \
         incompatible schema dialect and a renderer will read the wrong one"
    );

    let info = &doc["info"];
    assert!(
        info["title"].as_str().is_some_and(|t| !t.is_empty()),
        "{what}: OpenAPI requires a non-empty info.title"
    );
    assert_eq!(
        info["version"].as_str(),
        Some("1"),
        "info.version is the WIRE version in the /v1 prefix, not the crate \
         version. Binding it to CARGO_PKG_VERSION would put a second version \
         marker in the tree that has to move on every release, and would \
         invalidate a client's cached contract on a patch that changed no \
         endpoint"
    );
    assert_ne!(
        info["version"].as_str(),
        Some(env!("CARGO_PKG_VERSION")),
        "info.version has been bound to the crate version; see above"
    );

    let paths = doc["paths"].as_object().expect("paths is an object");
    assert!(
        !paths.is_empty(),
        "a document with no paths describes nothing"
    );

    let mut two_hundreds = 0usize;
    for (path, item) in paths {
        assert!(
            path.starts_with('/'),
            "path {path:?} does not start with a slash"
        );
        for method in METHODS {
            let Some(op) = item.get(method) else { continue };
            let responses = op["responses"]
                .as_object()
                .unwrap_or_else(|| panic!("{method} {path} declares no responses"));
            assert!(
                responses.keys().any(|c| c.starts_with('2')),
                "{method} {path} declares no 2xx response, so the document \
                 never says what a successful call returns"
            );
            two_hundreds += 1;
        }
    }
    assert!(
        two_hundreds >= MINIMUM_OPERATIONS,
        "{what}: walked only {two_hundreds} operations"
    );

    // Every `$ref` resolves, and every component compiles as a JSON Schema.
    let schemas = doc
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .expect("components.schemas");
    let mut refs: BTreeSet<String> = BTreeSet::new();
    collect_refs(&doc, &mut refs);
    assert!(
        refs.len() >= 10,
        "{what}: found only {} $refs; the walk is not reaching the operations",
        refs.len()
    );
    for r in &refs {
        let name = r.strip_prefix("#/components/schemas/").unwrap_or_else(|| {
            panic!("$ref {r:?} points outside components/schemas, which nothing resolves")
        });
        assert!(
            schemas.contains_key(name),
            "$ref {r:?} names a component the document does not declare"
        );
    }

    // No successful JSON response may be described as a bare object. utoipa
    // emits `{"type": "object"}` for a type it cannot see into, and a document
    // full of those is a route list wearing a schema's clothes: it tells a
    // client the body is JSON, which it already knew.
    let mut bare = Vec::new();
    for (path, item) in paths {
        for method in METHODS {
            let Some(op) = item.get(method) else { continue };
            let Some(schema) = op.pointer("/responses/200/content/application~1json/schema") else {
                continue;
            };
            let resolved = schema
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|r| r.strip_prefix("#/components/schemas/"))
                .and_then(|n| schemas.get(n))
                .unwrap_or(schema);
            let props = resolved
                .get("properties")
                .and_then(Value::as_object)
                .map_or(0, serde_json::Map::len);
            if props == 0 {
                bare.push(format!("{method} {path}"));
            }
        }
    }
    assert!(
        bare.is_empty(),
        "these declare a 200 body with no named properties, which describes \
         nothing a client can code against: {bare:?}"
    );

    for name in schemas.keys() {
        // Compiled with the whole component table as its root, so a
        // `#/components/schemas/X` reference inside resolves the way it does
        // in the document itself.
        let rooted = serde_json::json!({
            "components": { "schemas": schemas },
            "$ref": format!("#/components/schemas/{name}"),
        });
        jsonschema::validator_for(&rooted)
            .unwrap_or_else(|e| panic!("component {name} is not a valid JSON Schema: {e}"));
    }
}

/// Collect every `$ref` string in a document.
fn collect_refs(node: &Value, out: &mut BTreeSet<String>) {
    match node {
        Value::Object(map) => {
            if let Some(Value::String(r)) = map.get("$ref") {
                out.insert(r.clone());
            }
            for (_, v) in map {
                collect_refs(v, out);
            }
        }
        Value::Array(items) => {
            for v in items {
                collect_refs(v, out);
            }
        }
        _ => {}
    }
}

/// The JSON pointer of the first place two documents differ, with both values.
///
/// Depth-first and shallowest-first, so the answer is the outermost thing that
/// changed rather than a leaf inside it.
fn first_difference(a: &Value, b: &Value, at: &str) -> Option<String> {
    if a == b {
        return None;
    }
    match (a, b) {
        (Value::Object(x), Value::Object(y)) => {
            for k in x.keys().chain(y.keys()) {
                let here = format!("{at}/{k}");
                match (x.get(k), y.get(k)) {
                    (Some(l), Some(r)) => {
                        if let Some(found) = first_difference(l, r, &here) {
                            return Some(found);
                        }
                    }
                    (Some(_), None) => return Some(format!("{here} (only on disk)")),
                    (None, Some(_)) => return Some(format!("{here} (only generated)")),
                    (None, None) => {}
                }
            }
            None
        }
        (Value::Array(x), Value::Array(y)) => {
            if x.len() != y.len() {
                return Some(format!(
                    "{at} (disk has {}, generated has {})",
                    x.len(),
                    y.len()
                ));
            }
            x.iter()
                .zip(y)
                .enumerate()
                .find_map(|(i, (l, r))| first_difference(l, r, &format!("{at}/{i}")))
        }
        _ => Some(format!("{at}: disk {a} vs generated {b}")),
    }
}

/// The checked-in artifact is what generation produces right now.
///
/// The drift gate. Set `SIPNAB_BLESS_OPENAPI=1` to rewrite it.
#[test]
fn the_published_document_is_not_stale() {
    let generated = generate();
    let path = repo().join(ARTIFACT);

    if std::env::var_os("SIPNAB_BLESS_OPENAPI").is_some() {
        std::fs::write(&path, &generated).expect("write the artifact");
        eprintln!("blessed {ARTIFACT}");
        return;
    }

    let on_disk = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{ARTIFACT} is missing ({e}). Generate it with \
             `SIPNAB_BLESS_OPENAPI=1 cargo test --features full --test \
             openapi_contract_test`"
        )
    });

    // Compared as parsed JSON first, so the failure message names the
    // difference rather than a byte offset.
    let a: Value = serde_json::from_str(&on_disk).expect("the artifact is JSON");
    let b: Value = serde_json::from_str(&generated).expect("generation is JSON");
    if a != b {
        let old = documented_operations(&a);
        let new = documented_operations(&b);
        // Route sets first, because that is the difference an author usually
        // caused. But most differences are NOT routes -- a schema property, a
        // description, the version -- and reporting two empty route sets for
        // one of those tells the reader nothing, which is what this message did
        // when the version field was mutated to prove the gate fires.
        panic!(
            "{ARTIFACT} is stale.\n  only on disk: {:?}\n  only generated: {:?}\n               first differing field: {}\n\
             Regenerate with `SIPNAB_BLESS_OPENAPI=1 cargo test --features full \
             --test openapi_contract_test`",
            old.difference(&new).collect::<Vec<_>>(),
            new.difference(&old).collect::<Vec<_>>(),
            first_difference(&a, &b, "").unwrap_or_else(|| "(none found)".to_string())
        );
    }
    assert_eq!(
        on_disk, generated,
        "{ARTIFACT} parses the same but is not formatted the way the generator \
         writes it, so every regeneration would produce a diff"
    );
}

/// The two declarations of a dialog summary agree.
///
/// `tests/schemas/dialog.schema.json` and the `DialogSummary` component both
/// describe `output::model::DialogSummary`. Neither can be dropped — the
/// schema file is what `jsonschema` consumers use and the component is what
/// the OpenAPI document `$ref`s — so the only defense is to compare them.
#[test]
fn the_dialog_summary_component_agrees_with_the_shared_schema() {
    let doc = document();
    let component = doc
        .pointer("/components/schemas/DialogSummary")
        .expect("the document declares a DialogSummary component");

    let file = std::fs::read_to_string(repo().join("tests/schemas/dialog.schema.json"))
        .expect("read dialog.schema.json");
    let shared: Value = serde_json::from_str(&file).expect("dialog.schema.json is JSON");

    let names = |v: &Value| -> BTreeSet<String> {
        v["properties"]
            .as_object()
            .map(|m| m.keys().cloned().collect())
            .unwrap_or_default()
    };
    let required = |v: &Value| -> BTreeSet<String> {
        v["required"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default()
    };

    let component_names = names(component);
    assert!(
        component_names.len() >= 10,
        "the DialogSummary component declares only {} properties; the \
         comparison below would pass on an empty schema",
        component_names.len()
    );
    assert_eq!(
        component_names,
        names(&shared),
        "the DialogSummary OpenAPI component and \
         tests/schemas/dialog.schema.json describe different properties for \
         one Rust type"
    );
    assert_eq!(
        required(component),
        required(&shared),
        "the DialogSummary OpenAPI component and \
         tests/schemas/dialog.schema.json disagree about which properties are \
         always present"
    );
}

/// Every documented response validates against a body the server really sends.
///
/// The check that makes the rest of this file worth having. A schema nobody
/// compares to a response is prose with a `.json` extension: it can name a
/// field the handler dropped two releases ago and no test notices, because
/// every other test in this file compares the document to another document.
///
/// Runs the real binary over a real capture, follows the list routes to get
/// identifiers that exist, and validates each body against the component the
/// document says it will be.
#[test]
fn every_documented_response_matches_what_the_server_sends() {
    let doc = document();
    let schemas = doc
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .expect("components.schemas");

    let srv = server::ApiServer::spawn_with_pcap(G711, &[]);

    // Identifiers that exist in THIS capture, taken from the collections the
    // same way a client would.
    let dialogs = srv.get("/v1/dialogs").json();
    let call_id = dialogs["dialogs"][0]["call_id"]
        .as_str()
        .expect("the fixture must produce a dialog, or this test proves nothing")
        .to_string();
    let streams = srv.get("/v1/streams").json();
    let ssrc = streams["streams"][0]["ssrc"]
        .as_str()
        .expect("the fixture must produce a stream, or this test proves nothing")
        .to_string();

    let encode = |s: &str| -> String {
        s.bytes()
            .map(|b| match b {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                    (b as char).to_string()
                }
                _ => format!("%{b:02X}"),
            })
            .collect()
    };

    // Every documented GET whose 200 is JSON, with its path parameters filled
    // in. `/metrics` and `/health` answer text/plain and are checked by status
    // alone; `POST /v1/persistence` is not exercised here because it MUTATES a
    // gate, and a contract test must not be the thing that closes it.
    let mut checked: BTreeMap<String, String> = BTreeMap::new();
    for (method, path) in documented_operations(&doc) {
        if method != "get" {
            continue;
        }
        let Some(component) = doc
            .pointer(&format!(
                "/paths/{}/get/responses/200/content/application~1json/schema/$ref",
                path.replace('~', "~0").replace('/', "~1")
            ))
            .and_then(Value::as_str)
            .and_then(|r| r.strip_prefix("#/components/schemas/"))
        else {
            continue;
        };
        let url = path
            .replace("{call_id}", &encode(&call_id))
            .replace("{id}", &encode(&ssrc));
        checked.insert(url, component.to_string());
    }

    assert!(
        checked.len() >= 9,
        "only {} JSON GET routes were resolved to a component; the pointer \
         walk is broken and this test is validating almost nothing: {checked:?}",
        checked.len()
    );

    for (url, component) in &checked {
        let resp = srv.get(url);
        assert_eq!(resp.status, 200, "GET {url} answered {}", resp.status);
        let body: Value = serde_json::from_str(&resp.body)
            .unwrap_or_else(|e| panic!("GET {url} did not answer JSON: {e}"));

        let rooted = serde_json::json!({
            "components": { "schemas": schemas },
            "$ref": format!("#/components/schemas/{component}"),
        });
        let validator = jsonschema::validator_for(&rooted)
            .unwrap_or_else(|e| panic!("component {component} does not compile: {e}"));
        let errors: Vec<String> = validator
            .iter_errors(&body)
            .map(|e| format!("{} at {}", e, e.instance_path()))
            .collect();
        assert!(
            errors.is_empty(),
            "GET {url} answers a body the document's {component} schema \
             rejects:\n  {}",
            errors.join("\n  ")
        );
    }

    for (path, status) in [("/health", 200u16), ("/metrics", 200)] {
        assert_eq!(
            srv.get(path).status,
            status,
            "{path} is documented as {status}"
        );
    }
}
