//! Mermaid sequence diagram export.

use super::{FormattedMessage, Participant};

/// Generate a self-contained HTML page that renders a Mermaid sequence diagram.
///
/// The HTML embeds the Mermaid source and loads mermaid.js from CDN to render
/// it in any browser — no extensions or plugins needed.
pub fn export_mermaid_html(participants: &[Participant], messages: &[FormattedMessage]) -> String {
    let diagram = export_mermaid(participants, messages);
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>sipnab — Call Flow Diagram</title>
<style>
  body {{ background: #0d1117; color: #c9d1d9; font-family: system-ui, sans-serif; margin: 0; padding: 20px; }}
  h1 {{ font-size: 1.2em; color: #58a6ff; margin-bottom: 4px; }}
  p {{ font-size: 0.85em; color: #8b949e; margin-top: 0; }}
  .mermaid {{ background: #161b22; border-radius: 8px; padding: 20px; margin-top: 16px; }}
  pre {{ background: #161b22; padding: 12px; border-radius: 6px; font-size: 0.8em; overflow-x: auto; }}
</style>
</head>
<body>
<h1>sipnab Call Flow</h1>
<p>Generated by <a href="https://sipnab.com" style="color:#58a6ff">sipnab</a> — SIP &amp; RTP capture, analysis, and security</p>
<div class="mermaid">
{diagram}
</div>
<details style="margin-top:20px"><summary style="color:#8b949e;cursor:pointer">Mermaid source</summary>
<pre>{diagram}</pre>
</details>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
<script>mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});</script>
</body>
</html>"#,
        diagram = diagram
    )
}

/// Generate raw Mermaid sequenceDiagram source from participants and messages.
pub fn export_mermaid(participants: &[Participant], messages: &[FormattedMessage]) -> String {
    let mut out = String::from("sequenceDiagram\n");

    for p in participants {
        let id = sanitize_id(&p.addr);
        out.push_str(&format!("    participant {} as {}\n", id, p.label));
    }
    out.push('\n');

    for msg in messages {
        if msg.is_spacer {
            continue;
        }
        if msg.label.is_empty() {
            continue;
        }
        if msg.src_col >= participants.len() || msg.dst_col >= participants.len() {
            continue;
        }
        let src = sanitize_id(&participants[msg.src_col].addr);
        let dst = sanitize_id(&participants[msg.dst_col].addr);
        let arrow = if msg.is_response { "-->>" } else { "->>" };
        let label = &msg.label;

        out.push_str(&format!("    {}{}{}: {}\n", src, arrow, dst, label));
    }

    out
}

/// Sanitize an address string into a valid Mermaid participant ID.
fn sanitize_id(s: &str) -> String {
    s.replace([':', '.'], "_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use ratatui::style::Style;

    use crate::tui::call_flow::SelectionState;

    /// Helper to create a minimal FormattedMessage for testing.
    fn test_msg(
        src_col: usize,
        dst_col: usize,
        label: &str,
        is_response: bool,
    ) -> FormattedMessage {
        FormattedMessage {
            timestamp: String::new(),
            timestamp_style: Style::default(),
            label: label.to_string(),
            style: Style::default(),
            src_col,
            dst_col,
            pdd_note: None,
            extra_lines: Vec::new(),
            selected: false,
            call_id: String::new(),
            selection_state: SelectionState::Normal,
            is_response,
            raw_timestamp: Utc::now(),
            folded_count: 0,
            fold_label: None,
            is_spacer: false,
            sdp_badge: None,
            is_retransmission: false,
            is_rtp_bar: false,
        }
    }

    #[test]
    fn mermaid_basic() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        assert!(out.contains("sequenceDiagram"));
        assert!(out.contains("participant 10_0_0_1_5060 as alice"));
        assert!(out.contains("10_0_0_1_5060->>10_0_0_2_5060: INVITE"));
        assert!(out.contains("10_0_0_2_5060-->>10_0_0_1_5060: 200 OK"));
    }

    #[test]
    fn mermaid_skips_spacers() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let mut spacer = test_msg(0, 0, "", false);
        spacer.is_spacer = true;
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            spacer,
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        // Should have exactly 2 message lines (INVITE + 200 OK), no spacer
        let msg_lines: Vec<&str> = out.lines().filter(|l| l.contains("->>")).collect();
        assert_eq!(msg_lines.len(), 2);
    }

    #[test]
    fn mermaid_three_participants() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "proxy".to_string(),
            },
            Participant {
                addr: "10.0.0.3:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            test_msg(1, 2, "INVITE", false),
            test_msg(2, 1, "200 OK", true),
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        assert!(out.contains("participant 10_0_0_1_5060 as alice"));
        assert!(out.contains("participant 10_0_0_2_5060 as proxy"));
        assert!(out.contains("participant 10_0_0_3_5060 as bob"));
        // 2 requests use ->>, 2 responses use -->>
        let arrow_count = out.matches("->>").count();
        assert_eq!(
            arrow_count, 4,
            "expected 4 arrows (->>/-->>), got {arrow_count}"
        );
    }

    #[test]
    fn mermaid_fold_label_included() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let mut msg = test_msg(0, 1, "INVITE (auth retry)", false);
        msg.folded_count = 3;
        msg.fold_label = Some("3 msgs folded".to_string());
        let messages = vec![msg];
        let out = export_mermaid(&participants, &messages);
        assert!(
            out.contains("INVITE (auth retry)"),
            "mermaid output should contain fold label: {out}"
        );
    }

    #[test]
    fn sanitize_addresses() {
        assert_eq!(sanitize_id("10.0.0.1:5060"), "10_0_0_1_5060");
    }
}
