// SPDX-License-Identifier: MIT OR Apache-2.0

//! Mermaid sequence diagram export.
//!
//! Turns a prepared call flow (participants + formatted messages) into
//! Mermaid `sequenceDiagram` source, either raw (`export_mermaid`) or
//! wrapped in a self-contained dark-themed HTML page that renders it in a
//! browser (`export_mermaid_html`). Pure string generation — writing the
//! result to disk is the caller's job.

use super::{FormattedMessage, Participant};

/// Generate a fully self-contained HTML page holding a Mermaid sequence diagram.
///
/// The page loads NO external resources — no CDN script, stylesheet, font or
/// image — so it opens and reads on an air-gapped machine (the project's
/// no-external-deps stance for demos/exports). It embeds the Mermaid source
/// verbatim in a copyable block with short offline render instructions
/// (mermaid-cli / any Mermaid-aware editor). A pure-inline "Copy" button uses
/// only the browser's clipboard API — no library.
///
/// Tradeoff: the diagram is not rendered to a picture inside the file.
/// Auto-rendering would require vendoring mermaid.min.js (~3 MB) into every
/// export, which is unacceptable weight per file; embedding the (already
/// generated) source keeps the export tiny and offline-complete while leaving
/// a one-paste path to a rendered image.
///
/// # Arguments
/// * `participants` — endpoint columns, in ladder order.
/// * `messages` — prepared ladder rows; forwarded to `export_mermaid`.
///
/// # Returns
/// The complete HTML document as a string.
pub fn export_mermaid_html(participants: &[Participant], messages: &[FormattedMessage]) -> String {
    // HTML-escape the diagram before embedding it in the `<pre>` source view:
    // a label that closed the block and injected `<script>` would otherwise
    // execute. Labels are already neutralized at the Mermaid layer; this is
    // the HTML-context defense.
    let diagram = escape_html(&export_mermaid(participants, messages));
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>sipnab — Call Flow Diagram</title>
<style>
  body {{ background: #0d1117; color: #c9d1d9; font-family: system-ui, sans-serif; margin: 0; padding: 20px; }}
  h1 {{ font-size: 1.2em; color: #58a6ff; margin-bottom: 4px; }}
  p {{ font-size: 0.85em; color: #8b949e; margin-top: 0; }}
  .hint {{ background: #161b22; border-left: 3px solid #58a6ff; border-radius: 6px; padding: 12px 16px; margin-top: 16px; font-size: 0.85em; }}
  .hint code {{ color: #c9d1d9; }}
  ol {{ margin: 8px 0 0; padding-left: 20px; }}
  li {{ margin: 4px 0; }}
  button {{ background: #21262d; color: #c9d1d9; border: 1px solid #30363d; border-radius: 6px; padding: 6px 12px; font-size: 0.85em; cursor: pointer; margin-top: 12px; }}
  button:hover {{ background: #30363d; }}
  pre {{ background: #161b22; padding: 12px; border-radius: 6px; font-size: 0.85em; overflow-x: auto; color: #c9d1d9; margin-top: 12px; }}
</style>
</head>
<body>
<h1>sipnab Call Flow</h1>
<p>Generated by <a href="https://sipnab.com" style="color:#58a6ff">sipnab</a> — SIP &amp; RTP capture, analysis, and security</p>
<div class="hint">
  This file is fully self-contained — it needs no internet connection. It holds the
  <strong>Mermaid</strong> sequence-diagram source below. To render it as a picture:
  <ol>
    <li>Offline: install mermaid-cli (<code>npm i -g @mermaid-js/mermaid-cli</code>), save the source as <code>flow.mmd</code>, then run <code>mmdc -i flow.mmd -o flow.svg</code>.</li>
    <li>Or paste the source into any Mermaid-aware editor (VS Code Mermaid preview, Obsidian, or mermaid.live).</li>
  </ol>
</div>
<button onclick="navigator.clipboard&amp;&amp;navigator.clipboard.writeText(document.getElementById('src').textContent)">Copy Mermaid source</button>
<pre id="src">{diagram}</pre>
</body>
</html>"#,
        diagram = diagram
    )
}

/// Generate raw Mermaid sequenceDiagram source from participants and messages.
///
/// Each participant becomes a `participant <id> as <label>` line (id from
/// `sanitize_id`); each message becomes an arrow line, `->>` for requests
/// and `-->>` for responses, labeled with the message label. Synthetic
/// spacer and RTP-bar rows, rows with empty labels, and rows whose column
/// indices fall outside `participants` are skipped.
///
/// # Arguments
/// * `participants` — endpoint columns; `src_col`/`dst_col` index into this.
/// * `messages` — prepared ladder rows to emit as arrows.
///
/// # Returns
/// The Mermaid source text (always starting with `sequenceDiagram`).
pub fn export_mermaid(participants: &[Participant], messages: &[FormattedMessage]) -> String {
    let mut out = String::from("sequenceDiagram\n");

    for p in participants {
        let id = sanitize_id(&p.addr);
        out.push_str(&format!(
            "    participant {} as {}\n",
            id,
            escape_mermaid_label(&p.label)
        ));
    }
    out.push('\n');

    for msg in messages {
        if msg.is_spacer || msg.is_rtp_bar {
            continue;
        }
        if msg.label.is_empty() {
            continue;
        }
        if msg.src_col >= participants.len() || msg.dst_col >= participants.len() {
            continue;
        }
        let src = sanitize_id(&participants[msg.src_col].addr);
        let dst = sanitize_id(&participants[msg.dst_col].addr);
        let arrow = if msg.is_response { "-->>" } else { "->>" };
        let label = escape_mermaid_label(&msg.label);

        out.push_str(&format!("    {}{}{}: {}\n", src, arrow, dst, label));
    }

    out
}

/// Sanitize an address string into a valid Mermaid participant ID by
/// replacing `:` and `.` with `_` (e.g. `10.0.0.1:5060` → `10_0_0_1_5060`).
fn sanitize_id(s: &str) -> String {
    s.replace([':', '.'], "_")
}

/// Neutralize untrusted text (a SIP-derived message or participant label) for
/// embedding in Mermaid source. Newlines and carriage returns — which would
/// otherwise end the statement and let following text be parsed as diagram
/// syntax — become spaces, and the characters Mermaid treats specially are
/// replaced with its numeric entity codes (rendered back to the literal
/// glyph). Removing raw `<`/`>` here also means the HTML wrapper can never
/// receive label-injected markup.
fn escape_mermaid_label(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\n' | '\r' => out.push(' '),
            '#' => out.push_str("#35;"),
            ';' => out.push_str("#59;"),
            '<' => out.push_str("#60;"),
            '>' => out.push_str("#62;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Minimal HTML text-context escaping (`&`, `<`, `>`) for embedding generated
/// content in the exported HTML page.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Tests for the Mermaid export: participant/arrow emission, row skipping,
/// and ID sanitization.
#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use ratatui::style::Style;

    use crate::tui::call_flow::SelectionState;

    /// Helper to create a minimal `FormattedMessage` with the given columns,
    /// label and request/response flag; all other fields defaulted.
    fn test_msg(
        src_col: usize,
        dst_col: usize,
        label: &str,
        is_response: bool,
    ) -> FormattedMessage {
        FormattedMessage {
            timestamp: String::new(),
            timestamp_style: Style::default(),
            label: label.to_string(),
            style: Style::default(),
            src_col,
            dst_col,
            pdd_note: None,
            extra_lines: Vec::new(),
            selected: false,
            call_id: String::new(),
            selection_state: SelectionState::Normal,
            is_response,
            raw_timestamp: Utc::now(),
            folded_count: 0,
            fold_label: None,
            is_spacer: false,
            sdp_badge: None,
            is_retransmission: false,
            is_rtp_bar: false,
            raw_index: None,
            diagnosis_note: None,
        }
    }

    /// A label carrying newlines and Mermaid metacharacters is neutralized:
    /// the whole message stays on one arrow line and no raw `<`/`>`/newline
    /// from the label can break the diagram structure.
    #[test]
    fn mermaid_label_metacharacters_are_neutralized() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "a<b>".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![test_msg(0, 1, "INVITE\nBYE;#<x>", false)];
        let out = export_mermaid(&participants, &messages);

        // No raw `<` survives anywhere (the arrow syntax uses only `>`), and
        // the injected angle-bracketed spans are gone from both the message
        // label and the participant label.
        assert!(!out.contains('<'), "raw '<' must not survive: {out}");
        assert!(!out.contains("<x>"), "message label markup survived: {out}");
        assert!(
            !out.contains("a<b>"),
            "participant label markup survived: {out}"
        );
        // The injected newline must not split the label onto its own line —
        // the arrow and the tail of the label share one line.
        assert!(
            out.lines().any(|l| l.contains("->>") && l.contains("BYE")),
            "label newline must not break the arrow line: {out}"
        );
    }

    /// The HTML export escapes markup so a crafted label cannot inject a live
    /// `<script>` (or close the `<pre>`) in the generated page.
    #[test]
    fn mermaid_html_escapes_injected_markup() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![test_msg(0, 1, "x</pre><script>evil()</script>", false)];
        let html = export_mermaid_html(&participants, &messages);

        assert!(
            !html.contains("<script>evil"),
            "injected script tag must not appear live: {html}"
        );
        assert!(
            !html.contains("</pre><script>"),
            "must not be able to close the source block and inject: {html}"
        );
    }

    /// The exported HTML must be fully self-contained: no CDN/remote script
    /// or style, so the page reads offline (no-external-deps stance). The
    /// Mermaid source is embedded verbatim so the diagram is recoverable.
    #[test]
    fn mermaid_html_is_self_contained_no_remote_deps() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![test_msg(0, 1, "INVITE", false)];
        let html = export_mermaid_html(&participants, &messages);

        let lower = html.to_lowercase();
        assert!(
            !lower.contains("cdn."),
            "export must not load from a CDN: {html}"
        );
        // No remotely-loaded resources (scripts, styles, images). A plain
        // attribution hyperlink is fine — it isn't fetched to render.
        assert!(
            !lower.contains("src=\"http") && !lower.contains("<link"),
            "no remote script/style resource loads: {html}"
        );
        // Diagram source is embedded so it renders offline once pasted into
        // any Mermaid renderer.
        assert!(html.contains("sequenceDiagram"), "source embedded: {html}");
        assert!(html.contains("INVITE"), "message present: {html}");
    }

    /// A two-party INVITE/200 exchange emits both participants, a `->>`
    /// request arrow and a `-->>` response arrow.
    #[test]
    fn mermaid_basic() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        assert!(out.contains("sequenceDiagram"));
        assert!(out.contains("participant 10_0_0_1_5060 as alice"));
        assert!(out.contains("10_0_0_1_5060->>10_0_0_2_5060: INVITE"));
        assert!(out.contains("10_0_0_2_5060-->>10_0_0_1_5060: 200 OK"));
    }

    /// Spacer rows are omitted: only real messages become arrow lines.
    #[test]
    fn mermaid_skips_spacers() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let mut spacer = test_msg(0, 0, "", false);
        spacer.is_spacer = true;
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            spacer,
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        // Should have exactly 2 message lines (INVITE + 200 OK), no spacer
        let msg_lines: Vec<&str> = out.lines().filter(|l| l.contains("->>")).collect();
        assert_eq!(msg_lines.len(), 2);
    }

    /// RTP-bar rows are synthetic media bars whose columns are meaningless
    /// (src == dst == 0): they must not export as self-arrows, while the
    /// real message arrows around them survive.
    #[test]
    fn mermaid_skips_rtp_bars() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let mut bar = test_msg(0, 0, " RTP \u{00B7} PCMU ", false);
        bar.is_rtp_bar = true;
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            bar,
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        assert!(
            !out.contains("RTP"),
            "RTP bar must not become an arrow: {out}"
        );
        // Only the two real messages export as arrows.
        let msg_lines: Vec<&str> = out.lines().filter(|l| l.contains("->>")).collect();
        assert_eq!(msg_lines.len(), 2, "expected 2 arrows: {out}");
    }

    /// A three-party (proxied) flow lists all participants and one arrow
    /// per message, requests and responses alike.
    #[test]
    fn mermaid_three_participants() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "proxy".to_string(),
            },
            Participant {
                addr: "10.0.0.3:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let messages = vec![
            test_msg(0, 1, "INVITE", false),
            test_msg(1, 2, "INVITE", false),
            test_msg(2, 1, "200 OK", true),
            test_msg(1, 0, "200 OK", true),
        ];
        let out = export_mermaid(&participants, &messages);
        assert!(out.contains("participant 10_0_0_1_5060 as alice"));
        assert!(out.contains("participant 10_0_0_2_5060 as proxy"));
        assert!(out.contains("participant 10_0_0_3_5060 as bob"));
        // 2 requests use ->>, 2 responses use -->>
        let arrow_count = out.matches("->>").count();
        assert_eq!(
            arrow_count, 4,
            "expected 4 arrows (->>/-->>), got {arrow_count}"
        );
    }

    /// A fold-header row exports its (fold-annotated) label verbatim.
    #[test]
    fn mermaid_fold_label_included() {
        let participants = vec![
            Participant {
                addr: "10.0.0.1:5060".to_string(),
                label: "alice".to_string(),
            },
            Participant {
                addr: "10.0.0.2:5060".to_string(),
                label: "bob".to_string(),
            },
        ];
        let mut msg = test_msg(0, 1, "INVITE (auth retry)", false);
        msg.folded_count = 3;
        msg.fold_label = Some("3 msgs folded".to_string());
        let messages = vec![msg];
        let out = export_mermaid(&participants, &messages);
        assert!(
            out.contains("INVITE (auth retry)"),
            "mermaid output should contain fold label: {out}"
        );
    }

    /// `sanitize_id` maps dots and colons in an ip:port to underscores.
    #[test]
    fn sanitize_addresses() {
        assert_eq!(sanitize_id("10.0.0.1:5060"), "10_0_0_1_5060");
    }
}
