"""A docs page shows its description once, not twice.

Both site generators write a page's description into its front matter, and
page.html renders it as the grey lead under the title. Most docs/ sources open
with a paragraph that says the same thing, because on GitHub and the wiki that
paragraph IS the lead. On the site the reader got both, one under the other:
the glossary said "The VoIP and sipnab terms the other pages use" and then
"The VoIP and sipnab terms the rest of these pages use".

The generators mark such a page `lead_in_body = true`, and page.html then
skips the lead. The body paragraph is kept rather than the description,
because it is the longer of the two and carries facts the description drops.
"""

import importlib.util
import pathlib

SCRIPTS = pathlib.Path(__file__).resolve().parent.parent


def internals():
    spec = importlib.util.spec_from_file_location(
        "build_site_internals", SCRIPTS / "build-site-internals.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_a_paragraph_that_restates_the_description_is_a_repeat():
    lead_repeats = internals().lead_repeats
    assert lead_repeats(
        "The VoIP and sipnab terms the other pages use, each defined in one "
        "short entry by what it means in sipnab's output.",
        "The VoIP and sipnab terms the rest of these pages use, one short "
        "definition each. Every definition says what the term means in "
        "sipnab's output.\n\n## ACD\n",
    )


def test_a_paragraph_about_something_else_is_not():
    lead_repeats = internals().lead_repeats
    assert not lead_repeats(
        "Worked examples with real output: triage, filtering, HEP, TLS "
        "decryption and audio export.",
        "Recipe-style walkthroughs for the things people actually want to do. "
        "Each recipe states the problem first.\n",
    )


def test_the_first_paragraph_is_read_past_comments_and_headings():
    """The generators put a banner comment above the body; it is not prose."""
    lead_repeats = internals().lead_repeats
    assert lead_repeats(
        "Every method in the IANA registry and the RFC that defines it.",
        "<!-- Generated by a script -->\n\n"
        "Every method in the IANA registry, and the RFC that defines it.\n",
    )


def test_the_front_matter_carries_the_flag_only_when_asked():
    frontmatter = internals().frontmatter
    marked = frontmatter("T", 1, "D", False, lead_in_body=True)
    plain = frontmatter("T", 1, "D", False, lead_in_body=False)
    assert "lead_in_body = true" in marked
    assert "[extra]" in marked
    assert "lead_in_body" not in plain
    both = frontmatter("T", 1, "D", True, lead_in_body=True)
    assert both.count("[extra]") == 1, both
    assert "has_diagrams = true" in both and "lead_in_body = true" in both
