#!/usr/bin/env python3
"""Regenerate the status summary at the top of the backlog.

The file carries several hundred checkbox items across nine sections. The
convention is plain enough item by item -- `- [ ]` open, `- [x]` done -- and
useless in aggregate: nobody can answer "what is left in PV?" by scrolling
through 387 of them.

The summary is generated rather than hand-kept, because a hand-kept count is
wrong the first time somebody ticks a box and nobody notices for a month.
"""

import argparse
import pathlib
import re
import sys

BACKLOG = pathlib.Path(__file__).resolve().parent.parent / "docs/design/backlog.md"
BEGIN = "<!-- BACKLOG-STATUS: generated by scripts/backlog-status.py -- do not edit -->"
END = "<!-- /BACKLOG-STATUS -->"


def strip_generated(text: str) -> str:
    """The document without this script's own output.

    The generated block carries a `## Status` heading, so counting it as a
    section made the summary disagree with itself the moment it existed: one
    run wrote N sections, the next counted N+1 and reported the file stale
    forever. A generator that reads its own output has to remove it first.
    """
    if BEGIN not in text:
        return text
    start = text.index(BEGIN)
    stop = text.index(END, start) + len(END)
    return text[:start] + text[stop:]


def tally(text: str) -> list[tuple[str, int, int]]:
    """(section, open, done) in document order, for `## ` sections only."""
    rows, section, opened, done = [], None, 0, 0
    for line in strip_generated(text).splitlines():
        if line.startswith("## "):
            if section:
                rows.append((section, opened, done))
            section, opened, done = line[3:].strip(), 0, 0
        elif section and line.startswith("- [ ]"):
            opened += 1
        elif section and line.startswith("- [x]"):
            done += 1
    if section:
        rows.append((section, opened, done))
    return rows


def render(rows: list[tuple[str, int, int]]) -> str:
    total_open = sum(r[1] for r in rows)
    total_done = sum(r[2] for r in rows)
    out = [
        BEGIN,
        "",
        "## Status",
        "",
        f"**{total_open} open, {total_done} done** across {len(rows)} sections.",
        "Regenerate with `python3 scripts/backlog-status.py --apply`.",
        "",
        "| Section | Open | Done | Progress |",
        "|---|---:|---:|---|",
    ]
    for name, opened, done in rows:
        total = opened + done
        if total == 0:
            continue
        # A bar rather than a percentage: the eye reads position faster than it
        # reads a number, and this table exists to be scanned.
        filled = round(10 * done / total)
        bar = "#" * filled + "." * (10 - filled)
        label = name.split("—")[0].strip() if "—" in name else name
        out.append(f"| {label} | {opened} | {done} | `{bar}` |")
    out += ["", END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true", help="write the file")
    args = ap.parse_args()

    text = BACKLOG.read_text()
    block = render(tally(text))

    if BEGIN in text:
        start = text.index(BEGIN)
        stop = text.index(END, start) + len(END)
        updated = text[:start] + block + text[stop:]
    else:
        # First run: place it after the intro, before the first section.
        anchor = text.index("\n## ")
        updated = text[:anchor] + "\n" + block + "\n" + text[anchor:]

    if updated == text:
        print("backlog status is current")
        return 0
    if not args.apply:
        print("backlog status is STALE; run with --apply")
        return 1
    BACKLOG.write_text(updated)
    print("backlog status updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
