#!/usr/bin/env python3
"""Regenerate the status summary at the top of the backlog.

The file carries several hundred checkbox items across nine sections. The
convention is plain enough item by item -- `- [ ]` open, `- [x]` done -- and
useless in aggregate: nobody can answer "what is left in PV?" by scrolling
through 387 of them.

The summary is generated rather than hand-kept, because a hand-kept count is
wrong the first time somebody ticks a box and nobody notices for a month.
"""

import argparse
import pathlib
import re
import sys

# The working backlog is local and gitignored; docs/design/backlog.md is a
# tracked stub describing the convention. A clone without the local file --
# CI, or a fresh checkout -- has nothing to summarize, and that is not a
# failure.
BACKLOG = pathlib.Path(__file__).resolve().parent.parent / "docs/design/backlog.local.md"
BEGIN = "<!-- BACKLOG-STATUS: generated by scripts/backlog-status.py -- do not edit -->"
END = "<!-- /BACKLOG-STATUS -->"


def strip_generated(text: str) -> str:
    """The document without this script's own output.

    The generated block carries a `## Status` heading, so counting it as a
    section made the summary disagree with itself the moment it existed: one
    run wrote N sections, the next counted N+1 and reported the file stale
    forever. A generator that reads its own output has to remove it first.
    """
    if BEGIN not in text:
        return text
    start = text.index(BEGIN)
    stop = text.index(END, start) + len(END)
    return text[:start] + text[stop:]


# The four states, as docs/design/backlog.md documents them. In-progress and
# rejected are marked INSIDE the box's line rather than by inventing a third
# box character, because no renderer draws one: `- [~]` shows up as literal
# text, while an emoji carries the color the eye is looking for.
IN_PROGRESS = "\U0001F7E1"  # amber circle
REJECTED = "\u274C"  # red cross


def classify(line: str) -> str | None:
    """open / doing / done / rejected, or None when the line is not an item."""
    if line.startswith("- [ ]"):
        return "doing" if IN_PROGRESS in line else "open"
    if line.startswith("- [x]"):
        return "rejected" if REJECTED in line else "done"
    return None


def tally(text: str) -> list[tuple[str, int, int, int, int]]:
    """(section, open, doing, done, rejected) in order, for `## ` sections."""
    rows, section = [], None
    counts = {"open": 0, "doing": 0, "done": 0, "rejected": 0}
    for line in strip_generated(text).splitlines():
        if line.startswith("## "):
            if section:
                rows.append((section, counts["open"], counts["doing"], counts["done"], counts["rejected"]))
            section = line[3:].strip()
            counts = {"open": 0, "doing": 0, "done": 0, "rejected": 0}
        elif section:
            state = classify(line)
            if state:
                counts[state] += 1
    if section:
        rows.append((section, counts["open"], counts["doing"], counts["done"], counts["rejected"]))
    return rows


def render(rows: list[tuple[str, int, int, int, int]]) -> str:
    total_open = sum(r[1] for r in rows)
    total_doing = sum(r[2] for r in rows)
    total_done = sum(r[3] for r in rows)
    total_rejected = sum(r[4] for r in rows)
    out = [
        BEGIN,
        "",
        "## Status",
        "",
        f"**{total_open} open, {total_doing} in progress, {total_done} done, "
        f"{total_rejected} rejected** across {len(rows)} sections.",
        "Regenerate with `python3 scripts/backlog-status.py --apply`.",
        "",
        "| Section | Open | Doing | Done | Rejected | Progress |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for name, opened, doing, done, rejected in rows:
        # Rejected items are settled, so they count toward the bar the same way
        # done ones do: what the bar shows is how much is still to decide.
        total = opened + doing + done + rejected
        if total == 0:
            continue
        # A bar rather than a percentage: the eye reads position faster than it
        # reads a number, and this table exists to be scanned.
        filled = round(10 * (done + rejected) / total)
        bar = "#" * filled + "." * (10 - filled)
        label = name.split("—")[0].strip() if "—" in name else name
        out.append(f"| {label} | {opened} | {doing} | {done} | {rejected} | `{bar}` |")
    out += ["", END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true", help="write the file")
    args = ap.parse_args()

    if not BACKLOG.exists():
        print(f"no local backlog at {BACKLOG.name} — nothing to summarize")
        return 0

    text = BACKLOG.read_text()
    block = render(tally(text))

    if BEGIN in text:
        start = text.index(BEGIN)
        stop = text.index(END, start) + len(END)
        updated = text[:start] + block + text[stop:]
    else:
        # First run: place it after the intro, before the first section.
        anchor = text.index("\n## ")
        updated = text[:anchor] + "\n" + block + "\n" + text[anchor:]

    if updated == text:
        print("backlog status is current")
        return 0
    if not args.apply:
        print("backlog status is STALE; run with --apply")
        return 1
    BACKLOG.write_text(updated)
    print("backlog status updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
