#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md from the real dependency graph.

Attribution is a license obligation, not a courtesy: MIT and Apache-2.0 both
require the notice to travel with the binary, and the one copyleft component
sipnab touches (libasound, LGPL-2.1-or-later) requires saying so. A file like
this hand-maintained goes stale on the first `cargo update` and nobody notices,
which is exactly the failure mode `third_party_notices_are_current` exists to
prevent — it re-runs this script and fails if the committed file differs.

Scope, stated plainly because it bounds what the file is evidence of:

  * Rust crates reached from `sipnab` through *normal* and *build* edges with
    RELEASE_FEATURES below — the UNION of every feature set
    `.github/workflows/release.yml` compiles, so this covers every published
    binary rather than the largest one. Dev-dependencies are excluded — test
    harnesses are not linked into anything that ships.
  * Non-cargo libraries are listed by hand below, since they are resolved by the
    platform or by the cross image, not by cargo, and never appear in its
    metadata. Some are linked from the host at runtime; some are compiled into
    the static musl artifacts and therefore genuinely redistributed, which is a
    stronger obligation and is why each row says which case it is.

It records each crate's SPDX expression as declared in its own manifest. It is
an inventory, not a compendium of license texts; full texts live at the SPDX
identifiers given, and sipnab's own LICENSE-MIT / LICENSE-APACHE ship beside it.

Run from the repo root:  python3 scripts/build-third-party-notices.py [OUT]
Default OUT is THIRD-PARTY-NOTICES.md
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# Libraries cargo never sees: they come from the host's package manager or, for
# the static musl artifacts, from the cross images in docker/cross/. Maintained
# here by hand and gated by `third_party_notices_cover_system_libraries`.
#
# Two different obligations are mixed in this table on purpose, because the same
# library can fall under both depending on the artifact. Linking the host's copy
# at runtime redistributes nothing and carries no notice duty; compiling a copy
# into a static binary does redistribute it, and BSD-2/3-Clause both require the
# copyright notice and conditions to travel with binary distributions. Each row
# states which case applies rather than leaving the reader to infer it.
SYSTEM_LIBS = [
    (
        "libpcap",
        "BSD-3-Clause",
        "Packet capture; required by every build, since they all include the "
        "`native` feature. The gnu builds and the `.deb` link the host's shared "
        "libpcap and redistribute nothing. The static musl builds compile "
        "libpcap from source (see `docker/cross/`) and link it statically, so "
        "those artifacts do carry a copy of it — which is what BSD-3-Clause's "
        "binary-distribution clause covers.",
    ),
    (
        "netmap",
        "BSD-2-Clause",
        "Kernel-bypass capture backend, reached only as a libpcap capture "
        "module for `netmap:<ifname>` device names. It is header-only, so there "
        "is no netmap library to link: three headers from `luigirizzo/netmap` "
        "are compiled into libpcap's `pcap-netmap.o`. That object is inside the "
        "statically linked libpcap in the **musl artifacts only**, so netmap "
        "code is redistributed there and BSD-2-Clause requires this notice to "
        "accompany it. The gnu builds use the host's libpcap and carry no "
        "netmap code of sipnab's making.",
    ),
    (
        "libasound (alsa-lib)",
        "LGPL-2.1-or-later",
        "ALSA playback, reached only through the separately compiled "
        "`libsipnab_audio` plugin, which the binary `dlopen`s lazily. sipnab "
        "does not link it at load time, does not statically link it, and does "
        "not redistribute it — the `.deb` declares it as a Recommends and the "
        "static musl builds omit audio entirely. Dynamic linking against a "
        "system-provided copy is what keeps LGPL-2.1 section 6 satisfied "
        "without any obligation reaching sipnab's own source.",
    ),
]

# Crates offering a copyleft option alongside permissive ones. sipnab elects a
# permissive license in each case; recording the election is the point.
ELECTIONS = {
    "r-efi": ("MIT OR Apache-2.0 OR LGPL-2.1-or-later", "Apache-2.0"),
    "termina": ("MIT OR MPL-2.0", "MIT"),
}

HEADER = """<!-- Generated by scripts/build-third-party-notices.py — do not edit.
     Re-run the script and commit; third_party_notices_are_current fails if
     this file is stale. -->

# Third-party notices

sipnab itself is dual-licensed **MIT OR Apache-2.0** (see `LICENSE-MIT` and
`LICENSE-APACHE`). It builds on the work below.

This file is generated from the dependency graph, not maintained by hand, so it
cannot drift from what actually ships. It lists the Rust crates reached from
`sipnab` through normal and build edges with `--features full,bpf` — the union
of every feature set the release workflow compiles, of which the musl and
`noaudio` builds are subsets — plus the non-cargo libraries the artifacts
either link from the host or compile in. Dev-dependencies are excluded: test
harnesses are not part of any distributed artifact.

Each entry gives the SPDX expression the crate declares in its own manifest.
Full license texts are published at <https://spdx.org/licenses/> under those
identifiers.
"""


# The feature set the RELEASE builds ship, named ONCE.
#
# This file travels inside every artifact and MIT/Apache-2.0 both require it to,
# so it has to describe the binary beside it rather than a smaller build that
# happens to be convenient. It said `full` while `.github/workflows/release.yml`
# compiled the gnu targets with `full,bpf` — four crates (aya, aya-obj, object,
# assert_matches) present in the shipped binary and absent from its own notices.
# `third_party_notices_are_current` compares the committed file against THIS
# generator, so both sides of that gate agreed while both were wrong.
#
# `the_notices_and_sbom_cover_every_released_feature_set` runs release.yml's own
# feature-computing step for every matrix entry and fails if this string stops
# covering the union. Change what the release compiles and that gate names this
# line.
RELEASE_FEATURES = "full,bpf"


def cargo_metadata() -> dict:
    # No --filter-platform: `aya` is a `cfg(target_os = "linux")` dependency and
    # the notices must list it whoever runs the generator. Cargo's resolve graph
    # is all-platforms by default, which is the wanted behaviour here.
    out = subprocess.run(
        [
            "cargo",
            "metadata",
            "--format-version",
            "1",
            "--no-default-features",
            "--features",
            RELEASE_FEATURES,
        ],
        capture_output=True,
        check=True,
        text=True,
    )
    return json.loads(out.stdout)


def distributed_packages(meta: dict) -> list[tuple[str, str, str]]:
    """Crates reachable from `sipnab` via normal/build edges, excluding dev."""
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    packages = {p["id"]: p for p in meta["packages"]}
    workspace = set(meta["workspace_members"])

    roots = [i for i in workspace if packages[i]["name"] == "sipnab"]
    if not roots:
        raise SystemExit("ERROR: no `sipnab` package in workspace metadata")

    seen: set[str] = set()
    stack = list(roots)
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in nodes[current]["deps"]:
            # kind is null for normal deps, "build"/"dev" otherwise.
            kinds = {k.get("kind") for k in dep["dep_kinds"]}
            if None in kinds or "build" in kinds:
                stack.append(dep["pkg"])

    rows = []
    for pid in seen:
        if pid in workspace:
            continue
        pkg = packages[pid]
        license = pkg.get("license")
        if not license:
            raise SystemExit(
                f"ERROR: {pkg['name']} {pkg['version']} declares no license; "
                "add it to the notices by hand or vendor the text"
            )
        rows.append((pkg["name"], pkg["version"], license))
    return sorted(rows, key=lambda r: (r[0].lower(), r[1]))


def render(rows: list[tuple[str, str, str]]) -> str:
    """Render the whole notices document from the crate rows plus the hand list."""
    out = [HEADER, "", "## System and bundled libraries", ""]
    out.append(
        "Libraries cargo does not resolve. Most are provided by the host and "
        "linked at runtime, which redistributes nothing. The static musl "
        "artifacts are the exception: they compile libpcap — and, inside it, "
        "netmap — into the binary, so those two are genuinely redistributed "
        "there and their BSD notices are reproduced below for that reason. The "
        "last column says which case each library falls under."
    )
    out.append("")
    out.append("| Library | License | How sipnab uses it |")
    out.append("|---|---|---|")
    for name, license, note in SYSTEM_LIBS:
        out.append(f"| {name} | {license} | {note} |")

    elected = [(n, v, l) for n, v, l in rows if n in ELECTIONS]
    if elected:
        out += ["", "## Multi-licensed crates and the license elected", ""]
        out.append(
            "These offer a copyleft option alongside permissive ones. sipnab "
            "elects the permissive license named here."
        )
        out.append("")
        out.append("| Crate | Offered | Elected |")
        out.append("|---|---|---|")
        # Deduplicate on what is EMITTED, not on what was collected. The
        # version is dropped from this table -- the license election is a
        # property of the crate, not of a version -- so a crate vendored at two
        # versions passed `set()` as two distinct tuples and printed the same
        # row twice. r-efi, at 5.3.0 and 6.0.0, did exactly that. Two versions
        # declaring DIFFERENT licenses still produce two rows, and the check
        # below then fires on whichever disagrees with the recorded election.
        for name, license in sorted({(n, l) for n, _v, l in elected}):
            offered, choice = ELECTIONS[name]
            if license != offered:
                raise SystemExit(
                    f"ERROR: {name} now declares `{license}`, not `{offered}` — "
                    "re-check the election in ELECTIONS before regenerating"
                )
            out.append(f"| {name} | {offered} | **{choice}** |")

    out += ["", f"## Rust crates ({len(rows)})", ""]
    out.append("| Crate | Version | License |")
    out.append("|---|---|---|")
    for name, version, license in rows:
        out.append(f"| {name} | {version} | {license} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "THIRD-PARTY-NOTICES.md"
    meta = cargo_metadata()
    rows = distributed_packages(meta)
    out_path.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {len(rows)} crates + {len(SYSTEM_LIBS)} system libraries to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
