#!/usr/bin/env python3
"""Mirror `docs/examples.md` into the Zola site as the Cookbook page.

`docs/` is the single source of truth. The cookbook used to exist twice, by
hand: a 740-line site page and a 122-line `docs/examples.md`, sharing two of
their 36 commands. The wiki renders from `docs/`, so wiki readers were getting
roughly a third of the recipes — not as a stated subset, but as a page that
looked complete.

The transform is the same shape as `build-site-internals.py` and deliberately
imports that script's `DOCS_TO_SITE` map rather than restating it. Two copies
of one mapping is how the cookbook drifted in the first place, and this repo
has already deleted one duplicated rule for the same reason (see the removed
step 5c in `.githooks/pre-commit`).

Run from the repo root:  python3 scripts/build-site-cookbook.py [OUTPUT]
Default OUTPUT is `website/content/docs/cookbook.md`.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

SRC = "docs/examples.md"
TITLE = "Cookbook"
WEIGHT = 2
DESCRIPTION = (
    "Step-by-step recipes for every major sipnab feature: triage, filtering, "
    "HEP, TLS decryption, MCP, observability, security, audio export."
)

BANNER = (
    "<!-- Generated by scripts/build-site-cookbook.py from {src} — do not "
    "edit. Edit the source page and re-run the script; "
    "cookbook_mirror_is_current fails if this file is stale. -->\n\n"
)


def _internals():
    """Load `build-site-internals.py` for the shared doc->site page mapping.

    The filename has hyphens, so it is not importable as a module name; this is
    the supported way to load it by path. Importing is side-effect free — the
    script guards `main()` behind `__name__`.
    """
    path = Path(__file__).resolve().parent / "build-site-internals.py"
    spec = importlib.util.spec_from_file_location("_sipnab_site_internals", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_INT = _internals()
DOCS_TO_SITE: dict[str, str] = _INT.DOCS_TO_SITE
BLOB: str = _INT.BLOB

LINK_RE = re.compile(r"\]\(\s*(?:\./)?([^)\s]+?\.md)(#[^)\s]*)?\s*\)")

# Links into the code tree; a relative `packaging/deb/build-deb.sh` would
# otherwise survive verbatim onto a site page and resolve to nothing.
CODE_LINK_RE = re.compile(
    r"\]\(\s*((?:\.{1,2}/)*(?:src|tests|crates|benches|fuzz|scripts|contrib"
    r"|packaging|harness|ops|man|demos|\.github|\.githooks)(?:/[^)\s]*)?)\s*\)"
)


def rewrite_link(m: re.Match) -> str:
    target, anchor = m.group(1), (m.group(2) or "")
    if target.startswith(("http://", "https://")):
        return m.group(0)
    site = DOCS_TO_SITE.get(target)
    if site:
        return f"](@/docs/{site}{anchor})"
    return f"]({BLOB}/docs/{target}{anchor})"


def rewrite_code_link(m: re.Match) -> str:
    parts = [p for p in m.group(1).split("/") if p not in ("", ".")]
    while parts and parts[0] == "..":
        parts.pop(0)
    return f"]({BLOB}/{'/'.join(parts)})"


def render(text: str) -> str:
    title, body = _INT.strip_leading_h1(text)
    if title != TITLE:
        raise SystemExit(f"{SRC} H1 is {title!r}, expected {TITLE!r}")
    body = LINK_RE.sub(rewrite_link, body)
    body = CODE_LINK_RE.sub(rewrite_code_link, body)
    head = "\n".join(
        [
            "+++",
            f"title = {_INT.toml_str(TITLE)}",
            f"weight = {WEIGHT}",
            f"description = {_INT.toml_str(DESCRIPTION)}",
            "+++",
            "",
        ]
    )
    return head + BANNER.format(src=SRC) + body


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out = (
        Path(sys.argv[1])
        if len(sys.argv) > 1
        else root / "website" / "content" / "docs" / "cookbook.md"
    )
    rendered = render((root / SRC).read_text(encoding="utf-8"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    # The drift test renders into a temp dir to compare against the committed
    # copy, so the output is not necessarily under the repo root.
    try:
        shown = out.relative_to(root)
    except ValueError:
        shown = out
    print(f"  {SRC} -> {shown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
