#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md from the real dependency graph.

Attribution is a licence obligation, not a courtesy: MIT and Apache-2.0 both
require the notice to travel with the binary, and the one copyleft component
sipnab touches (libasound, LGPL-2.1-or-later) requires saying so. A file like
this hand-maintained goes stale on the first `cargo update` and nobody notices,
which is exactly the failure mode `third_party_notices_are_current` exists to
prevent — it re-runs this script and fails if the committed file differs.

Scope, stated plainly because it bounds what the file is evidence of:

  * Rust crates reached from `sipnab` through *normal* and *build* edges with
    `--features full` (the released gnu build; the musl build is that set minus
    `audio`, so this is a superset). Dev-dependencies are excluded — test
    harnesses are not linked into anything that ships.
  * System libraries linked at runtime are listed by hand below, since they are
    resolved by the platform, not by cargo, and never appear in its metadata.

It records each crate's SPDX expression as declared in its own manifest. It is
an inventory, not a compendium of licence texts; full texts live at the SPDX
identifiers given, and sipnab's own LICENSE-MIT / LICENSE-APACHE ship beside it.

Run from the repo root:  python3 scripts/build-third-party-notices.py [OUT]
Default OUT is THIRD-PARTY-NOTICES.md
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# Libraries the released binaries link at runtime. Cargo never sees these: they
# come from the host's package manager, so they are maintained here and gated
# by `third_party_notices_cover_system_libraries`.
SYSTEM_LIBS = [
    (
        "libpcap",
        "BSD-3-Clause",
        "Packet capture. Linked dynamically; required by every build that "
        "includes the `native` feature, which is all of them.",
    ),
    (
        "libasound (alsa-lib)",
        "LGPL-2.1-or-later",
        "ALSA playback, reached only through the separately compiled "
        "`libsipnab_audio` plugin, which the binary `dlopen`s lazily. sipnab "
        "does not link it at load time, does not statically link it, and does "
        "not redistribute it — the `.deb` declares it as a Recommends and the "
        "static musl builds omit audio entirely. Dynamic linking against a "
        "system-provided copy is what keeps LGPL-2.1 section 6 satisfied "
        "without any obligation reaching sipnab's own source.",
    ),
]

# Crates offering a copyleft option alongside permissive ones. sipnab elects a
# permissive licence in each case; recording the election is the point.
ELECTIONS = {
    "r-efi": ("MIT OR Apache-2.0 OR LGPL-2.1-or-later", "Apache-2.0"),
    "termina": ("MIT OR MPL-2.0", "MIT"),
}

HEADER = """<!-- Generated by scripts/build-third-party-notices.py — do not edit.
     Re-run the script and commit; third_party_notices_are_current fails if
     this file is stale. -->

# Third-party notices

sipnab itself is dual-licensed **MIT OR Apache-2.0** (see `LICENSE-MIT` and
`LICENSE-APACHE`). It builds on the work below.

This file is generated from the dependency graph, not maintained by hand, so it
cannot drift from what actually ships. It lists the Rust crates reached from
`sipnab` through normal and build edges with `--features full` — the released
gnu build, of which the musl build is a subset — plus the system libraries the
platform links at runtime. Dev-dependencies are excluded: test harnesses are not
part of any distributed artifact.

Each entry gives the SPDX expression the crate declares in its own manifest.
Full licence texts are published at <https://spdx.org/licenses/> under those
identifiers.
"""


def cargo_metadata() -> dict:
    out = subprocess.run(
        [
            "cargo",
            "metadata",
            "--format-version",
            "1",
            "--no-default-features",
            "--features",
            "full",
        ],
        capture_output=True,
        check=True,
        text=True,
    )
    return json.loads(out.stdout)


def distributed_packages(meta: dict) -> list[tuple[str, str, str]]:
    """Crates reachable from `sipnab` via normal/build edges, excluding dev."""
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    packages = {p["id"]: p for p in meta["packages"]}
    workspace = set(meta["workspace_members"])

    roots = [i for i in workspace if packages[i]["name"] == "sipnab"]
    if not roots:
        raise SystemExit("ERROR: no `sipnab` package in workspace metadata")

    seen: set[str] = set()
    stack = list(roots)
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in nodes[current]["deps"]:
            # kind is null for normal deps, "build"/"dev" otherwise.
            kinds = {k.get("kind") for k in dep["dep_kinds"]}
            if None in kinds or "build" in kinds:
                stack.append(dep["pkg"])

    rows = []
    for pid in seen:
        if pid in workspace:
            continue
        pkg = packages[pid]
        licence = pkg.get("license")
        if not licence:
            raise SystemExit(
                f"ERROR: {pkg['name']} {pkg['version']} declares no license; "
                "add it to the notices by hand or vendor the text"
            )
        rows.append((pkg["name"], pkg["version"], licence))
    return sorted(rows, key=lambda r: (r[0].lower(), r[1]))


def render(rows: list[tuple[str, str, str]]) -> str:
    out = [HEADER, "", "## System libraries", ""]
    out.append("Linked at runtime and provided by the host, never redistributed.")
    out.append("")
    out.append("| Library | Licence | How sipnab uses it |")
    out.append("|---|---|---|")
    for name, licence, note in SYSTEM_LIBS:
        out.append(f"| {name} | {licence} | {note} |")

    elected = [(n, v, l) for n, v, l in rows if n in ELECTIONS]
    if elected:
        out += ["", "## Multi-licensed crates and the licence elected", ""]
        out.append(
            "These offer a copyleft option alongside permissive ones. sipnab "
            "elects the permissive licence named here."
        )
        out.append("")
        out.append("| Crate | Offered | Elected |")
        out.append("|---|---|---|")
        for name, _version, licence in sorted(set(elected)):
            offered, choice = ELECTIONS[name]
            if licence != offered:
                raise SystemExit(
                    f"ERROR: {name} now declares `{licence}`, not `{offered}` — "
                    "re-check the election in ELECTIONS before regenerating"
                )
            out.append(f"| {name} | {offered} | **{choice}** |")

    out += ["", f"## Rust crates ({len(rows)})", ""]
    out.append("| Crate | Version | Licence |")
    out.append("|---|---|---|")
    for name, version, licence in rows:
        out.append(f"| {name} | {version} | {licence} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "THIRD-PARTY-NOTICES.md"
    meta = cargo_metadata()
    rows = distributed_packages(meta)
    out_path.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {len(rows)} crates + {len(SYSTEM_LIBS)} system libraries to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
