#!/usr/bin/env python3
"""Derive the homepage's GitHub star count from the GitHub API's answer.

pages.yml runs `gh api repos/<owner>/<repo>` at deploy time and gives this
script the JSON, which it reads and writes the data file
`website/templates/index.html` loads. Nothing commits the number, so the
homepage states the count as of its last deploy, and a build without the file
(a local `zola build`, or a deploy whose API call failed) shows no count
rather than a stale one.

The rule: `stargazers_count` of the answer for the repository named by
--repo, a whole number of zero or more. An answer for another repository, a
missing or non-integer field, or text that is not a JSON object is refused.

Usage:
    github-stars.py ANSWER --repo OWNER/NAME [--write PATH]

ANSWER is the saved API response, or `-` for standard input. Prints the
count. With --write, also writes `stars = N` to PATH as TOML, creating its
directory. Exits 1, writing nothing, when the answer is refused.
"""

import argparse
import json
import pathlib
import sys


class StarsError(Exception):
    """The answer does not state a star count for the named repository."""


def count(text: str, repo: str) -> int:
    """The star count `text`, a GitHub API repository object, states for `repo`."""
    try:
        doc = json.loads(text)
    except ValueError as e:
        raise StarsError(f"the answer is not JSON: {e}") from None
    if not isinstance(doc, dict):
        raise StarsError("the answer is not a repository object")
    name = doc.get("full_name")
    if not isinstance(name, str) or name.lower() != repo.lower():
        raise StarsError(f"the answer is for {name!r}, not {repo!r}")
    n = doc.get("stargazers_count")
    # bool is a subclass of int; true is not a count.
    if not isinstance(n, int) or isinstance(n, bool) or n < 0:
        raise StarsError(f"stargazers_count is {n!r}, not a whole number of zero or more")
    return n


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("answer", help="saved `gh api repos/OWNER/NAME` output, or - for stdin")
    ap.add_argument("--repo", required=True, help="the OWNER/NAME the answer must describe")
    ap.add_argument("--write", metavar="PATH", help="write `stars = N` here")
    args = ap.parse_args(argv)
    if args.answer == "-":
        text = sys.stdin.read()
    else:
        text = pathlib.Path(args.answer).read_text(errors="replace")
    try:
        n = count(text, args.repo)
    except StarsError as e:
        print(f"github-stars: {e}", file=sys.stderr)
        return 1
    if args.write:
        path = pathlib.Path(args.write)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("# Generated by scripts/github-stars.py. Not committed.\n" f"stars = {n}\n")
    print(n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
