#!/usr/bin/env python3
"""Derive the homepage's automated-test count from a `cargo test` run.

The one rule for the published number. ci.yml runs it on the output of the
Linux `cargo test --all-features` run, so a run it cannot count fails CI;
pages.yml runs it on that same output, taken from CI's run of the commit
being deployed, and writes the data file `website/templates/index.html`
reads. Nothing commits the number.

The rule: every line that STARTS with `test result`, one per test binary
(library, each integration test file, doctests), contributes its `passed`
figure, the fourth field when the line is split on spaces and semicolons. A
binary that reports FAILED, an output with no result line and a total of zero
are refused, so the number always describes a complete passing run.

Usage:
    published-test-count.py OUTPUT [--write PATH]

OUTPUT is the captured run, or `-` for standard input. Prints the count. With
--write, also writes `automated_tests = N` to PATH as TOML, creating its
directory. Exits 1, writing nothing, when the run cannot be counted.
"""

import argparse
import pathlib
import re
import sys

ANSI = re.compile(r"\x1b\[[0-9;]*m")
FIELDS = re.compile(r"[ ;]+")


class CountError(Exception):
    """The output does not describe a complete, passing run."""


def count(text: str) -> int:
    """Sum the passed column of every `test result` line in `text`."""
    total = 0
    lines = 0
    for raw in text.splitlines():
        line = ANSI.sub("", raw)
        if not line.startswith("test result"):
            continue
        fields = FIELDS.split(line)
        if len(fields) < 4 or not fields[3].isdigit():
            raise CountError(f"unreadable result line: {line!r}")
        if fields[2] != "ok.":
            raise CountError(f"a test binary reported {fields[2]!r}: {line!r}")
        total += int(fields[3])
        lines += 1
    if lines == 0:
        raise CountError("no `test result:` line, so this is not a completed `cargo test` run")
    if total == 0:
        raise CountError(f"{lines} result line(s) report 0 tests passed in total")
    return total


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("output", help="captured `cargo test` output, or - for stdin")
    ap.add_argument("--write", metavar="PATH", help="write `automated_tests = N` here")
    args = ap.parse_args(argv)

    if args.output == "-":
        text = sys.stdin.read()
    else:
        text = pathlib.Path(args.output).read_text(errors="replace")
    try:
        n = count(text)
    except CountError as e:
        print(f"published-test-count: {e}", file=sys.stderr)
        return 1

    if args.write:
        path = pathlib.Path(args.write)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Generated by scripts/published-test-count.py. Not committed.\n"
            f"automated_tests = {n}\n"
        )
    print(n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
