[Definition]
failregex = ^.* sipnab\[\d+\]: scanner_detected src=<HOST> ua=.* method=.*$
            ^.* sipnab\[\d+\]: reg_flood src=<HOST> count=\d+$
ignoreregex =
datepattern = ^%%Y-%%m-%%d %%H:%%M:%%S
