FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:main@sha256:b7452ab0229ccaf49fd17b207f148bb470362a8da3fdb903b332fbfc819367fc

# Build libpcap from source against musl for static linking
RUN apt-get update && apt-get install -y flex bison wget xz-utils && rm -rf /var/lib/apt/lists/* \
    && wget -q https://www.tcpdump.org/release/libpcap-1.10.5.tar.xz \
    && tar xf libpcap-1.10.5.tar.xz \
    && cd libpcap-1.10.5 \
    && CC=x86_64-linux-musl-gcc ./configure --host=x86_64-linux-musl --prefix=/usr/local/x86_64-linux-musl --disable-shared --without-libnl \
    && make -j$(nproc) \
    && make install \
    && cd .. && rm -rf libpcap-1.10.5 libpcap-1.10.5.tar.xz

RUN chown -R 1000:1000 /usr/local/x86_64-linux-musl
USER 1000
